#!/usr/bin/env python

# Author: Devendra Garg <dgarg@india.hp.com>

import os.path,sys

pathname='/proc/fs/lustre'
indent = 0

def logdir(msg,i):
    print ("%s%s:")%(getindent(i),msg)

def logname(filename,i):
    msg = ''
    try:
        f = open(filename)
        msg = f.readline() 
    except: msg = ''

    #trim new line
    if (msg != '') and (msg[ len(msg)-1 ] == '\n' ): msg = msg[:len(msg)-1]
    print ("%s%s ----> %s")%(getindent(i),os.path.basename(filename),msg)    

def getindent(i):
    space = ''
    for j in range(i): space = space + '  '
    return space

def visit1(path):

    global indent
    indent = indent + 1
 
    files = os.listdir(path)
    dirs = []
    print 
    if os.path.basename(path) == 'llite':
        logdir( os.path.basename(path)+' * -- Client Information -- * ',indent )
    elif  os.path.basename(path) == 'mds' :
        logdir( os.path.basename(path)+' * -- MDS Information -- * ',indent )
    elif  os.path.basename(path) == 'ost' :
        logdir( os.path.basename(path)+' * -- OST Information -- * ',indent )
    elif  os.path.basename(path) == 'ldlm' :
        logdir( os.path.basename(path)+' * -- LDLM Information -- * ',indent )
    else:
        logdir( os.path.basename(path),indent )
    for file in files:
        if os.path.isdir ( os.path.join(path,file) ):
            dirs.append( (os.path.join(path,file),indent+1 ))
        else:
            logname( os.path.join(path,file), indent+1 )
    for dir in dirs:
        visit1(dir[0])

    indent = indent - 1

def main():

    llitepath = os.path.join(pathname,'llite')
    visit1 ( llitepath )
    mdspath = os.path.join(pathname,'mds')
    visit1 ( mdspath )
    ostpath = os.path.join(pathname,'ost')
    visit1 ( ostpath )
    ldlmpath = os.path.join(pathname,'ldlm')
    visit1 ( ldlmpath )

if __name__ == "__main__":
    main()

