#!/bin/sh

MDS=NET_mds_tcp_UUID
MDSHOST=mds

/r/src/lustre/utils/lctl <<EOF
network tcp
close_uuid $MDS
del_uuid $MDS
connect $MDSHOST 988
add_uuid $MDS $MDSHOST
quit
EOF

/r/src/lustre/utils/lctl <<EOF
device \$RPCDEV
probe
newconn $MDS
quit
EOF
