# SPDX-License-Identifier: GPL-2.0

#
# This file is part of Lustre, http://www.lustre.org/
#

fscrypt_objs := crypto.o fname.o hkdf.o hooks.o keyring.o
fscrypt_objs += keysetup.o keysetup_v1.o policy.o
