#!/bin/sh

progname="${0##*/}"

warn ()
{
    [ "$1" ] && echo >&2
    [ "$1" ] && echo "$progname: $1" >&2
    [ "$1" ] && echo >&2
}

fatal ()
{
    warn "$2"
    exit "$1"
}

usage ()
{
    cat <<EOF
Usage: $progname lustretag
  where lustretag is a tag of the lustre-core module
EOF
}

# portalstag="HEAD"
portalstag="b1_4"
buildtag="HEAD"

case "$1" in
    '')
        warn "a lustretag is required."
	usage >&2
	exit 1
	;;
    --help | -h)
	usage
	exit 0
	;;

    # this is the branch table
    # keep this list sorted alphabetically!

    b1_4_bgl)
	portalstag="b1_4_bgl"
	;;

esac

cvs_cmd ()
{
    local dir="$1"
    local module="$2"
    local tag="$3"

    if [ -d "$dir" ] ; then
	echo "$progname: Updating $dir to -r $tag"
	( cd "$dir" && cvs up -r "$tag" )
    else
	echo "$progname: Checking out $dir from -r $tag"
	cvs co -r "$tag" -d "$dir" "$module"
    fi
}

cvs_cmd build build "$buildtag"
cvs_cmd portals portals "$portalstag"
cvs_cmd lustre lustre-core "$lustretag"
