# SPDX-License-Identifier: GPL-2.0

#
# This file is part of Lustre, http://www.lustre.org/
#

obj-m += osp.o
osp-objs := osp_dev.o osp_object.o osp_precreate.o osp_sync.o lproc_osp.o
osp-objs += lwp_dev.o osp_md_object.o osp_trans.o
