#!/bin/sh

. patchfns >/dev/null || . /usr/lib/patch-scripts/patchfns >/dev/null || { \
	echo "Impossible to find my library 'patchfns'."
	echo "Check your install, or go to the right directory"
	exit 1
}

desc1()
{
	PATCH=$(stripit $1)
	TXT=$P/txt/$PATCH.txt
	echo $PATCH.patch
	desc < $TXT
	echo
}

for i in $*
do
	desc1 $i
done
