#!/bin/sh

. patchfns >/dev/null || . /usr/lib/patch-scripts/patchfns >/dev/null || { \
	echo "Impossible to find my library 'patchfns'."
	echo "Check your install, or go to the right directory"
	exit 1
}

usage()
{
	echo "Usage: rolled-up-patch"
	exit 1
}

if [ $# != 0 ]
then
	usage
fi

RUP=$(mktemp /tmp/rup-XXXXXX)
rm -f $RUP

for i in $(cat applied-patches)
do
	patch_name=$(stripit $i)
	cat $P/pc/$patch_name.pc
done | sort | uniq > $RUP

kdiff $(cat $RUP)
rm -f $RUP
