#!/bin/sh

. patchfns >/dev/null || . /usr/lib/patch-scripts/patchfns >/dev/null || { \
	echo "Impossible to find my library 'patchfns'."
	echo "Check your install, or go to the right directory"
	exit 1
}

usage()
{
	echo "Usage: toppatch"
	exit 1
}

if [ $# != 0 ]
then
	usage
fi

if [ -e $DB ]
then
	TOP_PATCH=$(top_patch)
	if [ x$TOP_PATCH != x ]
	then
		echo $TOP_PATCH
	fi
fi
