/* -*- mode: c; c-basic-offset: 8; indent-tabs-mode: nil; -*-
 * vim:expandtab:shiftwidth=8:tabstop=8:
 */
#include <stdio.h>
#include <portals/api-support.h>
#include <portals/list.h>
#include <portals/lib-types.h>

#define BLANK_LINE()				\
do {						\
	printf ("\n");				\
} while (0)

#define COMMENT(c)				\
do {						\
	printf ("        /* "c" */\n");		\
} while (0)

#define STRINGIFY(a) #a

#define CHECK_DEFINE(a)						\
do {								\
	printf ("        LASSERT ("#a" == "STRINGIFY(a)");\n");	\
} while (0)

#define CHECK_VALUE(a)					\
do {							\
	printf ("        LASSERT ("#a" == %d);\n", a);	\
} while (0)

#define CHECK_MEMBER_OFFSET(s,m)		\
do {						\
	CHECK_VALUE (offsetof (s, m));	\
} while (0)

#define CHECK_MEMBER_SIZEOF(s,m)			\
do {							\
	CHECK_VALUE (sizeof (((s *)0)->m));	\
} while (0)

#define CHECK_MEMBER(s,m)			\
do {						\
	CHECK_MEMBER_OFFSET (s, m);		\
	CHECK_MEMBER_SIZEOF (s, m);		\
} while (0)

#define CHECK_STRUCT(s)				\
do {						\
        COMMENT ("Checks for struct "#s);	\
	CHECK_VALUE (sizeof (s));	\
} while (0)

void
check_ptl_handle_wire (void)
{
	CHECK_STRUCT (ptl_handle_wire_t);
	CHECK_MEMBER (ptl_handle_wire_t, wh_interface_cookie);
	CHECK_MEMBER (ptl_handle_wire_t, wh_object_cookie);
}

void
check_ptl_ack (void)
{
	CHECK_STRUCT (ptl_ack_t);
	CHECK_MEMBER (ptl_ack_t, mlength);
	CHECK_MEMBER (ptl_ack_t, dst_wmd);
	CHECK_MEMBER (ptl_ack_t, match_bits);
	CHECK_MEMBER (ptl_ack_t, length);
}

void
check_ptl_put (void)
{
	CHECK_STRUCT (ptl_put_t);
	CHECK_MEMBER (ptl_put_t, ptl_index);
	CHECK_MEMBER (ptl_put_t, ack_wmd);
	CHECK_MEMBER (ptl_put_t, match_bits);
	CHECK_MEMBER (ptl_put_t, length);
	CHECK_MEMBER (ptl_put_t, offset);
	CHECK_MEMBER (ptl_put_t, hdr_data);
}

void
check_ptl_get (void)
{
	CHECK_STRUCT (ptl_get_t);
	CHECK_MEMBER (ptl_get_t, ptl_index);
	CHECK_MEMBER (ptl_get_t, return_wmd);
	CHECK_MEMBER (ptl_get_t, match_bits);
	CHECK_MEMBER (ptl_get_t, length);
	CHECK_MEMBER (ptl_get_t, src_offset);
	CHECK_MEMBER (ptl_get_t, return_offset);
	CHECK_MEMBER (ptl_get_t, sink_length);
}

void
check_ptl_reply (void)
{
	CHECK_STRUCT (ptl_reply_t);
	CHECK_MEMBER (ptl_reply_t, dst_wmd);
	CHECK_MEMBER (ptl_reply_t, dst_offset);
	CHECK_MEMBER (ptl_reply_t, length);
}

void
check_ptl_hdr (void)
{
	CHECK_STRUCT (ptl_hdr_t);
	CHECK_MEMBER (ptl_hdr_t, dest_nid);
	CHECK_MEMBER (ptl_hdr_t, src_nid);
	CHECK_MEMBER (ptl_hdr_t, dest_pid);
	CHECK_MEMBER (ptl_hdr_t, src_pid);
	CHECK_MEMBER (ptl_hdr_t, type);
	CHECK_MEMBER (ptl_hdr_t, msg);
}

void
check_ptl_magicversion (void)
{
	CHECK_STRUCT (ptl_magicversion_t);
	CHECK_MEMBER (ptl_magicversion_t, magic);
	CHECK_MEMBER (ptl_magicversion_t, version_major);
	CHECK_MEMBER (ptl_magicversion_t, version_minor);
}

int
main (int argc, char **argv)
{
	printf ("void lib_assert_wire_constants (void)\n"
		"{\n");

	COMMENT ("Wire protocol assertions generated by 'wirecheck'");
	BLANK_LINE ();
	
	COMMENT ("Constants...");
	CHECK_DEFINE (PORTALS_PROTO_MAGIC);
	CHECK_DEFINE (PORTALS_PROTO_VERSION_MAJOR);
	CHECK_DEFINE (PORTALS_PROTO_VERSION_MINOR);

	CHECK_VALUE (PTL_MSG_ACK);
	CHECK_VALUE (PTL_MSG_PUT);
	CHECK_VALUE (PTL_MSG_GET);
	CHECK_VALUE (PTL_MSG_REPLY);
	CHECK_VALUE (PTL_MSG_HELLO);

	check_ptl_handle_wire ();
	check_ptl_ack ();
	check_ptl_put ();
	check_ptl_get ();
	check_ptl_reply ();
	check_ptl_hdr ();
	check_ptl_magicversion ();
	
	printf ("}\n\n");
	
	return (0);
}
