# Copyright (C) 2001  Cluster File Systems, Inc.
#
# This code is issued under the GNU General Public License.
# See the file COPYING in this distribution
MODULE = obdfs.o
CFILES=  flushd.c rw.c file.c dir.c sysctl.c super.c namei.c symlink.c

include ../make.rules
