#!/bin/bash

[ -f .mergeinfo ] && . ./.mergeinfo

FILES=`cvs-modified-files.pl $1`
TMP=`mktemp /tmp/cvslog-XXXXXXXX`
if [ -f $TMP ]; then
	[ -f .mergeinfo ] && \
		echo "CVS: Update $child from $parent ($date)" >> $TMP
	echo "CVS: did you update the ChangeLog for a bug fix?" >> $TMP
	echo "CVS: b=" >> $TMP
	echo "CVS: r=" >> $TMP

	cat $1 >> $TMP
	cp $TMP $1
	rm $TMP
fi

if [ "${FILES:+have_files}"x = have_filesx ]; then
  echo Diffing $1 : $FILES
  cvs diff -wbBup $FILES 2>/dev/null | sed "s/^/CVS: /" >>$1
fi
#gnuclient $1 || vi $1
[ "$EDITOR" ] || EDITOR=vi

$EDITOR $1
