#! /bin/sh
# license-status - Display the status of files in the current directory
# Copyright (c) 2001, 2010, Oracle and/or its affiliates. All rights reserved.
#
# This code is issued under the GNU General Public License.
# See the file COPYING in this distribution
#
# Gordon Matzigkeit <gord@fig.org>, 2001-09-27

for f in `find . -type f | sort`; do
 case "$f" in
 *~ | *.orig | *.gz | */config.* | *.o | \
 */CVS/* | */.cvsignore | */.depfiles/* | \
 */COPYING | */ChangeLog)
  continue
  ;;
 esac

 if head -20 "$f" | egrep -e 'GNU' > /dev/null; then
  echo "gpled $f"
 elif head -20 "$f" | egrep -e '\([Cc]\)' > /dev/null; then
  echo "copyrighted $f"
 else
  echo "bare $f"
 fi
done | sort
