#!/bin/sh -x
# Copyright (C) 2001  Cluster File Systems, Inc.
#
# This code is issued under the GNU General Public License.
# See the file COPYING in this distribution

mknod -m 0600 /dev/obd0 c 186 0
mknod -m 0600 /dev/obd1 c 186 1
mknod -m 0600 /dev/obd2 c 186 2
mknod -m 0600 /dev/obd3 c 186 3
mknod -m 0600 /dev/obd4 c 186 4
mknod -m 0600 /dev/obd5 c 186 5
mknod -m 0600 /dev/obd6 c 186 6
mknod -m 0600 /dev/obd7 c 186 7
