#! /bin/sh
# nodelustre - Start and stop Lustre on MCR nodes
# Copyright 2008 Sun Microsystems, Inc.
# Gord Eagle <gord@clusterfs.com>, 2002-09-10

# Set this to the shared config file.
MASTER_CONFIG=http://emcri/lustre.xml
CONFIG=/etc/lustre/lustre.xml
COMPUTE_NODE=client

LCONF=/usr/local/cfs/lustre/utils/lconf
WGET=wget

case "$1" in
start | stop)
  # Fetch the config file.  We can't use --output-document because it
  # makes Wget ignore timestamping.
  if test -n "$MASTER_CONFIG"; then
    (cd `echo "$CONFIG" | sed 's%/[^/]*$%%'` && \
      $WGET --timestamping "$MASTER_CONFIG") || exit $?
  fi

  # Map all client nodes to the COMPUTE_NODE virtual node.
  if test -n "$COMPUTE_NODE" && nodeattr compute; then
    node=" --node $COMPUTE_NODE"
  else
    node=
  fi

  # If we're stopping, do the lconf cleanup.
  if test "$1" = stop; then
    cleanup=' --cleanup'
  else
    cleanup=
  fi

  $LCONF$cleanup$node "$CONFIG"
  ;;

*)
  echo "$0 {start|stop}" 1>&2
  exit 1
  ;;
esac

exit 0
