#!/bin/sh
TMP=${TMP:-/tmp}
cat /tmp/ogdb-`hostname` | while read JUNK M JUNK; do
	MOD="../$M"
	MAP=`echo $MOD | sed -e 's/\.o$/.map/'`
	MODNAME=`basename $MOD | sed -e 's/\.o$//'`

	nm $MOD > $MAP
	echo namelist -a $PWD/$MOD 
	echo symtab -a $PWD/$MAP $MODNAME
done
