#!/bin/sh
TMP=${TMP:-/tmp}
LCMD=$TMP/lkcd-cmds-`hostname`
echo "Storing LKCD module info in $LCMD"
cat /tmp/ogdb-`hostname` | while read JUNK M JUNK; do
	DIR=`dirname $M`
	DIR=`cd $PWD/../$DIR; pwd`
	MOD="$DIR/`basename $M`"
	MAP=`echo $MOD | sed -e 's/\.o$/.map/'`
	MODNAME=`basename $M | sed -e 's/\.o$//'`

	nm $MOD > $MAP
	echo namelist -a $MOD  | tee -a $LCMD
	echo symtab -a $MAP $MODNAME | tee -a $LCMD
done
