#!/bin/sh
MNT=${MNT:-/mnt/lustre}
DIR=${DIR:-$MNT/`hostname`}
#[ -e /proc/sys/portals/debug ] && echo 0 > /proc/sys/portals/debug 
mkdir -p $DIR
TGT=$DIR/client.txt
SRC=${SRC:-/usr/lib/dbench/client.txt}
[ ! -e $TGT -a -e $SRC ] && echo "copying $SRC to $TGT" && cp $SRC $TGT
SRC=/usr/lib/dbench/client_plain.txt
[ ! -e $TGT -a -e $SRC ] && echo "copying $SRC to $TGT" && cp $SRC $TGT
cd $DIR
echo "running 'dbench $@' on $PWD at `date`"
dbench -c client.txt $@
