#!/bin/sh

set -vx

SRCDIR="`dirname $0`"
. $SRCDIR/common.sh

test_fail() {
	echo $1 > /proc/sys/lustre/fail_loc
	shift
	echo "Running '$*'"
	$* &
	sleep 1
	kill -9 $!

        echo 0 > /proc/sys/lustre/fail_loc
	umount /mnt/lustre || fail "cannot unmount /mnt/lustre"
	setup_mount || fail "cannot remount /mnt/lustre"
}

[ "`mount | grep /mnt/lustre`" ] || . llsetup.sh "$@" || exit -1

# OBD_FAIL_OST_OPEN_NET: OST will discard open request packet
touch /mnt/lustre/foo
test_fail 0x208 cat /mnt/lustre/foo

echo "Done."
