#!/bin/sh
SIZE=5g
COUNT=0
[ -z "$VERIFY" ] && VERIFY="-+d"
[ -z "$ODIR" ] && ODIR="-I"
[ -z "$REC" ] && REC=64
FILE=/mnt/lustre/test.$$
[ $1 ] && SIZE=$1
rm -f endiozone
echo 0 > /proc/sys/portals/debug
while date; do
	echo "Test #$COUNT"
	iozone $VERIFY $ODIR -r $REC -i 0 -i 1 -f $FILE -s $SIZE 2>&1 || exit $?
	COUNT=`expr $COUNT + 1`
	[ -f endiozone ] && rm endiozone && exit 0
done | tee /tmp/iozone.log
