#!/bin/bash

# Run multiop in the background, but wait for it to print
# "PAUSING" to its stdout before returning from this function.

PTLDEBUG=${PTLDEBUG:--1}
LUSTRE=${LUSTRE:-`dirname $0`/..}
MULTIOP=${MULTIOP:-multiop}
. $LUSTRE/tests/test-framework.sh

TMP=${TMP:-/tmp}
MULTIOP_PID_FILE=${MULTIOP_PID_FILE:-$TMP/multiop_bg.pid}
rm -f $MULTIOP_PID_FILE

multiop_bg_pause $*
rc=$?
[ "$rc" = 0 ] && echo $! > $MULTIOP_PID_FILE
exit $rc
