#!/bin/sh
#
# Script which does some basic tests to ensure we haven't regressed.
# Probably a good idea to run this before doing any checkins.
# In the future this can become more fancy, but it's OK for now.

SRCDIR="`dirname $0`"

export PATH=/sbin:/usr/sbin:$SRCDIR:$PATH

. $SRCDIR/common.sh

ERROR=
SRC=/etc
[ "$COUNT" ] || COUNT=1000

setup_opts $@

[ "`mount | grep $OSCMT`" ] || echo | sh llsetup.sh $@ || exit 1

# let's start slowly here...
echo "touching $OSCMT"
touch $OSCMT || fail "can't touch $OSCMT" 2
HOSTS=$OSCMT/hosts.$$
echo "copying /etc/hosts to $HOSTS"
cp /etc/hosts $HOSTS || fail "can't cp /etc/hosts to $HOSTS" 3
echo "comparing /etc/hosts and $HOSTS"
diff -u /etc/hosts $HOSTS || fail "$HOSTS different" 4
#echo "renaming $HOSTS to $HOSTS.ren"
#mv $HOSTS $HOSTS.ren || fail "can't rename $HOSTS to $HOSTS.ren" 5
#echo "copying /etc/hosts to $HOSTS again"
#cp /etc/hosts $HOSTS || fail "can't cp /etc/hosts to $HOSTS again" 6
#echo "truncating $HOSTS"
#> $HOSTS || fail "can't truncate $HOSTS" 8
#echo "removing $HOSTS"
#rm $HOSTS || fail "can't remove $HOSTS" 9

DST=$OSCMT/runtest.$$
# let's start slowly here...
echo "creating $DST"
mkdir $DST || fail "can't mkdir $DST" 10

# ok, that hopefully worked, so let's do a little more
FILES=`find $SRC -type f | head -$COUNT`
echo "copying files from $SRC to $DST$SRC"
tar cf - $FILES | tar xvf - -C $DST || fail "copying $SRC" 11

echo "comparing newly copied files"
for f in $FILES; do
	diff -q $f $DST/$f || ERROR=11
done

[ "$ERROR" ] && fail "old and new files are different" $ERROR

sh llcleanup.sh $@

echo | sh llrsetup.sh $@ || exit 20
echo "comparing previously copied files"
for f in $FILES; do
	diff -q $f $DST/$f || ERROR=22
done

[ "$ERROR" ] && fail "old and new files are different on second diff" $ERROR

sh llcleanup.sh $@
echo | sh llrsetup.sh $@ || exit 31

#echo "renaming $HOSTS.ren to $HOSTS"
#mv $HOSTS.ren $HOSTS || fail "can't rename $HOSTS.ren to $HOSTS" 32
echo "truncating $HOSTS"
> $HOSTS || fail "can't truncate $HOSTS" 34
echo "removing $HOSTS"
rm $HOSTS || fail "can't remove $HOSTS again" 36
echo "removing $DST"
rm -r $DST || fail "can't remove $DST" 37

sh llcleanup.sh $@
