#!/bin/sh
#
# Script which does some basic tests to ensure we haven't regressed.
# Probably a good idea to run this before doing any checkins.
# In the future this can become more fancy, but it's OK for now.

SRCDIR="`dirname $0`"

export PATH=/sbin:/usr/sbin:$SRCDIR:$PATH

. $SRCDIR/common.sh

ERROR=

[ "`mount | grep /mnt/lustre`" ] || echo | sh llsetup.sh $@ || exit 1

# let's start slowly here...
touch /mnt/lustre || fail "can't touch /mnt/lustre" 2
echo "copying /etc/hosts to /mnt/lustre/hosts"
cp /etc/hosts /mnt/lustre || fail "can't cp /etc/hosts" 3
echo "comparing /etc/hosts and /mnt/lustre/hosts"
diff -u /etc/hosts /mnt/lustre/hosts || fail "/etc/hosts copy different" 4

# ok, that hopefully worked, so let's do a little more
FILES=`find /etc -type f`
echo "copying files from /etc to /mnt/lustre"
tar cf - $FILES | tar xvf - -C /mnt/lustre || fail "copying /etc" 10

echo "comparing newly copied files"
for f in $FILES; do
	diff -q $f /mnt/lustre/$f || ERROR=11
done

[ "$ERROR" ] && fail "old and new files are different" 11

sh llcleanup.sh $@

echo | sh llrsetup.sh $@ || exit 20
echo "comparing previously copied files"
diff -u /etc/hosts /mnt/lustre/hosts || fail "/etc/hosts is now different" 21

for f in $FILES; do
	diff -q $f /mnt/lustre/$f || ERROR=22
done

[ "$ERROR" ] && fail "old and new files are different on second diff" 23

sh llcleanup.sh $@
echo | sh llrsetup.sh $@ || exit 24

echo "truncating /etc/hosts"
> /etc/hosts || fail "can't cp /etc/hosts" 4
echo "removing /mnt/lustre/hosts"
rm /mnt/lustre/hosts || fail "can't remove /mnt/lustre/hosts" 25

rm -r /mnt/lustre/etc || fail "can't remove /mnt/lustre/etc" 26

sh llcleanup.sh $@
