#!/bin/bash

active_nid="uml3"
target_name=`echo $2 | sed 's/_.*//'`

config="$lustre_path/tests/failover.xml"
lustre_path="/r/home/umka/work/cfs/lustre"

if test "x$1" = "xFAILED_IMPORT"; then
        $lustre_path/utils/lconf --recover --select $target_name=$active_nid --tgt_uuid $2 \
        --client_uuid $3 --conn_uuid $4 $config
fi
