# Copyright (C) 2001  Cluster File Systems, Inc.
#
# This code is issued under the GNU General Public License.
# See the file COPYING in this distribution

MODULE = obdclass.o
bin_PROGRAMS = obdcontrol

CFILES = genops.c proc_lustre.c class_obd.c sysctl.c 

include ../make.rules
