.TH L_GETSEPOL 8 2024-08-29 Lustre "Lustre Configuration Utilities"
.SH NAME
l_getsepol \- Lustre SELinux policy info
.SH SYNOPSIS
.SY l_getsepol
.YS
.SH DESCRIPTION
.B l_getsepol
generates the Lustre SELinux policy info to set as reference on a nodemap with
.BR lctl-nodemap_set_sepol (8).
The info string describing the SELinux policy has the following syntax:
.EX
.IB MODE : NAME : VERSION : HASH
.EE
where:
.TP 8
.B MODE
is a digit telling if SELinux is in Permissive mode (0) or Enforcing mode (1)
.TP
.B NAME
is the name of the SELinux policy
.TP
.B VERSION
is the version of the SELinux policy
.TP
.B HASH
is the computed hash of the binary representation of the policy, as
exported in /etc/selinux/<name>/policy/policy.<version>
.PP
.B l_getsepol
should be run on a client node known to enforce the right SELinux policy.
.SH EXAMPLES
.EX
.B # l_getsepol
SELinux status info: 1:mls:31:c79984bb42c0151cb0d8cc34a196a6ca95c2791190c403804efb3e9d81b6109c
.EE
.SH AVAILABILITY
.B l_getsepol
is part of the
.BR lustre (7)
filesystem package since release 2.13.0
.\" Added in commit v2_12_50-90-gc61168239e
.SH SEE ALSO
.BR lustre (7),
.BR lctl-nodemap-set-sepol (8)
