.TH LCTL-DEVICE_LIST 8 2024-08-13 Lustre "Lustre Configuration Utilities"
.SH NAME
lctl-device_list \- show all local Lustre Object Based Devices
.SH SYNOPSIS
.SY "lctl device_list"
.RB [ --target | -t ]
.RB [ --yaml | -y ]
.SY "lctl dl"
is the same command.
.YS
.SH DESCRIPTION
.B lctl device_list
reports details about the local Lustre OBDs. The information reported for the
OBD are the type, name, and UUID. Also reported are the device number, status
and reference count of the OBD device. The device number is needed for lctl
--device argument.
.SH OPTIONS
.TP
.BR -t ", " --target
Retrieve the servers' export NID that communicates with the local OBD.
.TP
.BR -y ", " --yaml
An option provided so that the OBD information can be provided in YAML format
.SH EXAMPLES
.EX
.B # lctl --device_list -t -y
.EE
.SH AVAILABILITY
.B lctl device_list
and
.B lctl dl
are subcommands of
.BR lctl (8)
and are distributed as part of the
.BR lustre (7)
filesystem package.
.B lctl device_list
was added in release 0.6.0
.\" Added in commit 0.5.3-2-g3629f184eb
.B lctl dl
was added in release 0.5.0
.\" Added in commit 0.4.2-6-gbefd9c343f
.SH SEE ALSO
.BR lustre (7),
.BR lctl (8)
