.TH LCTL-LCFG_CLEAR 8 2024-08-13 Lustre "Lustre Configuration Utilities"
.SH NAME
lctl-lcfg_clear \- clear filesystem config llog
.SH SYNOPSIS
.SY "lctl lcfg_clear"
.IR FSNAME | DEVNAME
.YS
.SH DESCRIPTION
.B lcfg_clear
(alias
.BR clear_conf )
is run on the MGS node, with the MGS device mounted with the
.B -o nosvc
flag. It cleans up any records marked
.I SKIP
from the configuration files stored in the
.I CONFIGS/
directory. If
.I DEVNAME
is given, then the specific logs for
that filesystem (e.g.
.IR testfs-MDT0000 )
are processed. Otherwise, if a filesystem name is given, then all
configuration files are cleared. The previous configuration log is
backed up on the MGS disk with the suffix
.IR 'config.timestamp.bak' ,
such as
.IR 'testfs-MDT0000.1476454535.bak' .
.SH AVAILABILITY
.B lctl-lcfg_clear
is part of the
.BR lustre (7)
filesystem package since release 2.11.0
.\" Added in commit v2_10_58_0-78-g2a9518b1f8
.SH SEE ALSO
.BR lctl (8),
.BR lctl-lcfg_erase (8),
.BR lctl-lcfg_fork (8),
.BR lctl-llog_catlist (8),
.BR lctl-llog_clear (8),
.BR lctl-llog_print (8),
.BR lctl-snapshot-create (8),
.BR lctl-snapshot-destroy (8)
