.TH LCTL-LCFG_ERASE 8 2024-08-13 Lustre "Lustre Configuration Utilities"
.SH NAME
lctl-lcfg_erase \- erase filesystem config llog
.SH SYNOPSIS
.SY "lctl lcfg_erase"
.I FSNAME
.YS
.SH DESCRIPTION
.B lcfg_erase
(alias
.BR erase_lcfg )
permanently erases the configuration for the filesystem named
.IR FSNAME .
The MGS should be mounted when this command is run. It can be used to
remove the backup configuration or delete inactive filesystem (or snapshot)
from a shared MGS. To see the available configuration logs, use
.B lctl
.BR llog_catlist .
.SH AVAILABILITY
.B lctl-lcfg_erase
is part of the
.BR lustre (7)
filesystem package since release 2.10.0
.\" Added in commit v2_9_54_0-28-g61718da8ba
.SH SEE ALSO
.BR lctl (8),
.BR lctl-lcfg_clear (8),
.BR lctl-lcfg_fork (8),
.BR lctl-llog_catlist (8),
.BR lctl-snapshot-create (8),
.BR lctl-snapshot-destroy (8)
