.TH LFS-RM_ENTRY 8 2025-12-20 "Lustre" "Lustre Utilities"
.SH NAME
lfs-rm_entry, lfs-rmentry \- remove only filename from directory
.SH SYNOPSIS
.SY "lfs rm_entry"
.I DIRECTORY
.YS
.SY "lfs rmentry"
.I DIRECTORY
.YS
.SH DESCRIPTION
In cases where an MDT is permanently offline, or if there is an inconsistency
between MDT directory contents and files (e.g. broken striped directory), the
.B lfs rm_entry
(or
.BR "lfs rmentry" )
command removes
.B only
the directory entry name from the parent directory, but does not try to delete
the inode corresponding to the filename. The MDT inode itself (or a local agent
inode in the case of DNE remote entries) will still remain on the MDT filesystem,
and will be reconnected to the internal MDT lost+found directory when
.BR e2fsck (8)
is next run. Since the MDT inode itself is not deleted, any OST objects
referenced by this inode will also not be destroyed, so no space will be released.
.SH WARNING
The main reason to use
.B lfs rm_entry
is to remove directory entry names that are permanently inaccessible,
in order to allow them to be restored from backup, or to avoid application
errors when accessing these names. It should not be used to delete files
that are normally accessible.
.PP
This command can only be run by the root user (administrator).
.SH EXAMPLES
Remove a directory entry that references an inaccessible remote MDT:
.RS
.EX
.B # lfs rm_entry /mnt/lustre/broken_dir
.EE
.RE
.SH AVAILABILITY
The
.B lfs rm_entry
command is part of the
.BR lustre (7)
filesystem package.
.SH SEE ALSO
.BR e2fsck (8),
.BR lfs (1),
.BR lfs-rmfid (1)
