#!/bin/sh

MAIL=$BASEDIR/tmp/$TESTUSER.name
OUT=$BASEDIR/tmp/$TESTUSER.bonnie++
DATE=`date +"%Y%m%d %H:%M:%S"`
TESTNAME=bonnie++-small
TESTDESC="bonnie++"

COMMAND="bonnie++ -q -d $MOUNT/$TESTUSER -s 10 -r 0 -n 10"
timed_run 600 pdsh -E -S -s -w $SINGLECLIENT $COMMAND &> $OUT

rc=$?

if [ $rc -eq 0 ]
	then RESULT="pass"
        else RESULT="fail"
fi

. $BASEDIR/tests/begin_buffalo_email
echo "Log: $TESTNAME" >> $MAIL
echo "Command line: $COMMAND" >> $MAIL
/bin/cat $OUT >> $MAIL
echo "LogEnd: $TESTNAME" >> $MAIL
/bin/rm $OUT
$SENDMAIL < $MAIL
/bin/rm $MAIL

exit $rc
