#!/bin/sh

MAIL=$BASEDIR/tmp/$TESTUSER.name
OUT=$BASEDIR/tmp/$TESTUSER.dbench
DATE=`date +"%Y%m%d %H:%M:%S"`
TESTNAME=dbench-small
TESTDESC="dbench 5"

COMMAND="dbench -c $BASEDIR/tests/client.txt 5"
timed_run 300 pdsh -E -S -s -w $SINGLECLIENT \
"cd $MOUNT/$TESTUSER && $COMMAND" &> $OUT

rc=$?

if [ $rc -eq 0 ]
	then RESULT="pass"
        else RESULT="fail"
fi

. $BASEDIR/tests/begin_buffalo_email
echo "Log: $TESTNAME" >> $MAIL
echo "Command line: $COMMAND" >> $MAIL
/bin/cat $OUT >> $MAIL
echo "LogEnd: $TESTNAME" >> $MAIL
/bin/rm $OUT
$SENDMAIL < $MAIL
/bin/rm $MAIL

exit $rc
