#!/bin/sh

MAIL=$BASEDIR/tmp/$TESTUSER.name
OUT=$BASEDIR/tmp/$TESTUSER.fsx
DATE=`date +"%Y%m%d %H:%M:%S"`
TESTNAME=fsx-small
TESTDESC="fsx"

COMMAND="fsx -N 1000 $TESTUSER"
timed_run 180 pdsh -E -S -s -w $SINGLECLIENT \
"cd $MOUNT/$TESTUSER && $COMMAND" &> $OUT

rc=$?

if test $rc -eq 0
	then RESULT="pass"
        else RESULT="fail"
fi

. $BASEDIR/tests/begin_buffalo_email
echo "Log: $TESTNAME" >> $MAIL
echo "Command line: $COMMAND" >> $MAIL
/bin/cat $OUT >> $MAIL
echo "LogEnd: $TESTNAME" >> $MAIL
/bin/rm $OUT
$SENDMAIL < $MAIL
/bin/rm $MAIL

exit $rc
