#!/bin/sh

MAIL=$BASEDIR/tmp/$TESTUSER.name
OUT=$BASEDIR/tmp/$TESTUSER.iozone
DATE=`date +"%Y%m%d %H:%M:%S"`
TESTNAME=iozone-small
TESTDESC="iozone"

COMMAND="iozone -a -M -R -g 10M -q 512k -i0 -i1 -f $MOUNT/$TESTUSER/iozone"
timed_run 300 pdsh -E -S -s -w $SINGLECLIENT $COMMAND &> $OUT

rc=$?

if [ $rc -eq 0 ]
	then RESULT="pass"
        else RESULT="fail"
fi

. $BASEDIR/tests/begin_buffalo_email
echo "Log: $TESTNAME" >> $MAIL
echo "Command line: $COMMAND" >> $MAIL
/bin/cat $OUT >> $MAIL
echo "LogEnd: $TESTNAME" >> $MAIL
/bin/rm $OUT
$SENDMAIL < $MAIL
/bin/rm $MAIL

exit $rc
