#!/bin/sh

MAIL=$BASEDIR/tmp/$TESTUSER.mail
OUT=$BASEDIR/tmp/$TESTUSER.simul
DATE=`date +"%Y%m%d %H:%M:%S"`
TESTNAME=simul
TESTDESC="simul"

COMMAND="simul -d $MOUNT/$TESTUSER"
timed_run 120 pdsh -E -S -w $CLIENTS $COMMAND > $OUT.stdout 2> $OUT.stderr

rc=$?

if test $rc -eq 0
	then RESULT="pass"
        else RESULT="fail"
fi

. $BASEDIR/tests/begin_buffalo_email
echo "Log: $TESTNAME" >> $MAIL
echo "Command line: $COMMAND" >> $MAIL
/bin/cat $OUT.stdout >> $MAIL
/bin/cat $OUT.stderr >> $MAIL
/bin/rm $OUT.stdout
/bin/rm $OUT.stderr
echo "LogEnd: $TESTNAME" >> $MAIL
$SENDMAIL < $MAIL
/bin/rm $MAIL

exit $rc
