
if WITH_STDFD_DEV
STDFD_DEV_CPPFLAGS =-DSTDFD_DEV=1 -I$(top_srcdir)/dev/stdfd
else
STFD_DEV_CPPFLAGS =
endif

if WITH_SOCKETS_DRIVER
SOCKETS_CPPFLAGS=-DWITH_SOCKETS=1
else
SOCKETS_CPPFLAGS=
endif

DEV_CPPFLAGS = $(STDFD_DEV_CPPFLAGS)

AM_CPPFLAGS = \
	-D_POSIX_C_SOURCE=199506L -D_XOPEN_SOURCE=600 \
	$(AUTOMOUNT) $(ZERO_SUM_MEMORY) $(DEV_CPPFLAGS) $(SOCKETS_CPPFLAGS) \
	$(DEFER_INIT_CWD) -I$(top_srcdir)/include 
