#!/bin/sh

#PORTALS_MYNID=${PORTALS_MYNID:-`hostname -i`}
PORTALS_MYNID=${PORTALS_MYNID:-"172.16.1.1"}
LUSTRE_MOUNT_POINT=${LUSTRE_MOUNT_POINT:-"/mnt/lustre"}
LD_PRELOAD=${LD_PRELOAD:-"/usr/lib/liblustre.so"}

export PORTALS_MYNID
export LUSTRE_MOUNT_POINT
export LD_PRELOAD

exec $@
