# SPDX-License-Identifier: GPL-2.0

#
# This file is part of Lustre, http://www.lustre.org/
#

obj-m += ofd.o
ofd-objs := ofd_dev.o ofd_obd.o ofd_fs.o ofd_trans.o ofd_objects.o ofd_io.o
ofd-objs += lproc_ofd.o ofd_oss.o ofd_dlm.o ofd_lvb.o ofd_access_log.o
