# SPDX-License-Identifier: GPL-2.0

#
# This file is part of Lustre, http://www.lustre.org/
#

obj-m += ec_test.o kinode.o obd_test.o obd_mod_rpcs_test.o
obj-$(CONFIG_LUSTRE_FS_SERVER) += ldlm_extent.o llog_test.o
