#!/bin/bash

echo "=== Router Buffers ==========================="
echo
test -e /proc/sys/lnet/buffers && cat /proc/sys/lnet/buffers
echo
echo "=== NIs ======================================"
echo
test -e /proc/sys/lnet/nis && cat /proc/sys/lnet/nis
echo
echo "=== Peers ===================================="
echo
test -e /proc/sys/lnet/peers && cat /proc/sys/lnet/peers

