#!/bin/sh

lnds=$(echo k{sock,qsw,gm,{open,i,v,o2,c}ib,ra,ptl,mx}lnd)

if lctl network down > /dev/null 2>&1; then
    for mod in $lnds; do
	if grep "^$mod" /proc/modules >/dev/null 2>&1; then
	    rmmod $mod
	fi
    done

    rmmod lnet 
    rmmod libcfs
fi
