LUSTRE_NODE_ROLE_UNDEFINED = 'UNDEFINED'
LUSTRE_NODE_ROLE_CLIENT = 'CLIENT'
LUSTRE_NODE_ROLE_ROUTER = 'ROUTER'
LUSTRE_NODE_ROLE_OSS = 'OSS'
LUSTRE_NODE_ROLE_OST = 'OST'
LUSTRE_NODE_ROLE_MGS = 'MGS'
LUSTRE_NODE_ROLE_MDT = 'MDT'
LUSTRE_NODE_ROLE_MDS = 'MDS'
LUSTRE_NODE_ROLE_MGT = 'MGT'


