# SPDX-License-Identifier: GPL-2.0

#
# This file is part of Lustre, http://www.lustre.org/
#

obj-m += ksocklnd.o

ksocklnd-objs := \
	socklnd.o \
	socklnd_cb.o \
	socklnd_lib.o \
	socklnd_modparams.o \
	socklnd_proto.o
