# Copyright (C) 2001  Cluster File Systems, Inc.
#
# This code is issued under the GNU General Public License.
# See the file COPYING in this distribution
all: perms

perms:
	@-chmod a+x *.sh

clean: 
	-rm -f *~ *.orig

install:
