#ifndef PTL_DISPATCH_H
#define PTL_DISPATCH_H

/*
 * include/dispatch.h
 *
 * Dispatch table header and externs for remote side
 * operations
 *
 * Generated by idl
 *
 */

#include <portals/lib-p30.h>
#include <portals/arg-blocks.h>

extern int do_PtlGetId(nal_cb_t * nal, void *private, void *args, void *ret);
extern int do_PtlNIStatus(nal_cb_t * nal, void *private, void *args, void *ret);
extern int do_PtlNIDist(nal_cb_t * nal, void *private, void *args, void *ret);
extern int do_PtlNIDebug(nal_cb_t * nal, void *private, void *args, void *ret);
extern int do_PtlMEAttach(nal_cb_t * nal, void *private, void *args, void *ret);
extern int do_PtlMEInsert(nal_cb_t * nal, void *private, void *args, void *ret);
extern int do_PtlMEPrepend(nal_cb_t * nal, void *private, void *args,
                           void *ret);
extern int do_PtlMEUnlink(nal_cb_t * nal, void *private, void *args, void *ret);
extern int do_PtlTblDump(nal_cb_t * nal, void *private, void *args, void *ret);
extern int do_PtlMEDump(nal_cb_t * nal, void *private, void *args, void *ret);
extern int do_PtlMDAttach(nal_cb_t * nal, void *private, void *args,
                                   void *ret);
extern int do_PtlMDBind(nal_cb_t * nal, void *private, void *args,
                                 void *ret);
extern int do_PtlMDUpdate_internal(nal_cb_t * nal, void *private, void *args,
                                   void *ret);
extern int do_PtlMDUnlink(nal_cb_t * nal, void *private, void *args,
                                   void *ret);
extern int do_PtlEQAlloc_internal(nal_cb_t * nal, void *private, void *args,
                                  void *ret);
extern int do_PtlEQFree_internal(nal_cb_t * nal, void *private, void *args,
                                 void *ret);
extern int do_PtlACEntry(nal_cb_t * nal, void *private, void *args, void *ret);
extern int do_PtlPut(nal_cb_t * nal, void *private, void *args, void *ret);
extern int do_PtlGet(nal_cb_t * nal, void *private, void *args, void *ret);
extern int do_PtlFailNid (nal_cb_t *nal, void *private, void *args, void *ret);

extern char *dispatch_name(int index);
#endif
