.TH l_getgroups 1 "Jul 7, 2008" Lustre "utilities"
.SH NAME
l_getgroups \- Handle Lustre user/group cache upcall
.SH SYNOPSIS
.B "l_getgroups [-v] [-d | mdsname] uid"
.br
.B "l_getgroups [-v] -s"
.SH DESCRIPTION
The group upcall file contains the path to an executable that, when
properly installed, is invoked to resolve a numeric UID to a group
membership list.
.LP
.B l_getgroups
is the reference implementation of the user/group cache upcall
.SH FILES
/{proc,sys}/fs/lustre/mds/mds-service/group_upcall
.SH SEE ALSO
Lustre Programming Interfaces section of Lustre Operations Manual.
