.TH l_getidentity 1 "Dec 7, 2016" Lustre "utilities"
.SH NAME
l_getidentity \- Handle Lustre user/group cache upcall
.SH SYNOPSIS
.B "l_getidentity {-d | mdtname} uid"
.SH DESCRIPTION
The identity upcall command specifies the path to an executable that,
when properly installed, is invoked to resolve the numeric
.I uid
to a group membership list.
.LP
.B l_getidentity
is the reference implementation of the user/group cache upcall.
This command is normally run directly by the Lustre MDS service
and specifies the
.I mdtname
argument for the MDT that should be updated.
.br
.SS "The permissions file"
.PP
.I /etc/lustre/perm.conf
supports a flat file database of permissions in the format
.br
 UID<space>NID<space>perm1,perm2,...,permN
.br

.br
where
.B perm
is one of:
.I [no]setuid
.I [no]setgid
.I [no]setgrp
.I [no]rmtacl
.I [no]rmtown
.br
 
.br
.BR nss (5)
modules can be enabled for auth handling by adding a 
.B lookup 
command with a list of nss modules to the first line of
.BR perm.conf
.br
At the time of writing, known 
.BR nss (5)
modules include:
.BR lustre ", " nss_files ", " ldap ", " nis ", " sss ", and" systemd
additional modules may be documented in
.BR nsswitch.conf (5)
or installed separately.
.br
 
.br
.BR nss (5)
modules are searched in order. Once an entry is found in
the module no further modules are searched.
.br
 
.br
A special
.B lustre
module is used to enable lustre specific password and group
auth by way of
.B /etc/lustre/passwd
and
.B /etc/lustre/group
.br
 
.br
For historical reasons
.B nss_files
was needed to use the
.BR nss (5)
.B files
module.
This alias is now deprecated and will be removed in a future release.
.SH OPTIONS
.TP
.B -d
Run in debug mode and print supplementary groups information for
.I uid
to
.B stdout
instead of updating Lustre.
.SH EXAMPLES
The identity upcall command can be specified via:
.br
.RI "lctl set_param mdt." mdtname .identity_upcall= path_to_upcall
.br
 
.br
Enable lustre auth and ldap
.br
 [/etc/lustre/perm.conf]
.br
.B lookup lustre ldap
.br
 
.br
 [/etc/lustre/passwd]
.br
  root:x:0:0:root:/root:/bin/bash
.br
  ...
.br
 [/etc/lustre/group]
.br
  root:x:0:root
.br
  ...
.br
Lustre passwd and group files use the same format as the system 
.BR passwd (5)
and
.BR group (5)
files.
.br
In this configuration root is local to the cluster and all other perms are delegated to ldap.
.br
.SH LIMITS
A maximum of 8 nss modules can be enabled.
.b4
.SH FILES
.RI /{proc,sys}/fs/lustre/mdt/ mdt-service /identity_upcall
.br
.RI /etc/lustre/perm.conf
.br
.RI /etc/lustre/passwd
.br
.RI /etc/lustre/group
.SH SEE ALSO
.BR nss (5),
.BR passwd (5),
.BR group (5)
.br
Lustre Programming Interfaces section of Lustre Operations Manual.
