.TH LCTL-NODEMAP_DEL_IDMAP 8 2024-08-14 Lustre "Lustre Configuration Utilities"
.SH NAME
lctl-nodemap_del_idmap \- delete an existing idmap from a nodemap
.SH SYNOPSIS
.SY "lctl nodemap_del_idmap"
.BI --name " NODEMAP_NAME"
.BR --idtype " {" uid | gid | projid }
.B --idmap
.IR CLIENTID [- CLIENTID_END ]: FSID [- FSID_END ]
.YS
.SH DESCRIPTION
.B nodemap_del_idmap
deletes an idmap from a nodemap.
Users or groups or projects in the nodemap with that ID will be squashed,
if the trusted flag is not enabled.
.SH OPTIONS
.TP
.BI --name " NODEMAP_NAME"
The name of the nodemap that this idmap should be deleted from.
.TP
.BR --idtype " {" uid | gid | projid }
Either "uid" or "gid" or "projid" depending on if it is a user or group or
project ID mapping that is to be removed.
.TP
.BI --idmap " CLIENTID\fR[" - CLIENTID_END\fR] : FSID\fR[ - FSID_END\fR]
The identity map to delete.
.SH EXAMPLES
.EX
.B # lctl nodemap_del_idmap --name remotesite --idtype uid --idmap 2001:1001
.B # lctl nodemap_del_idmap --name remotesite --idtype gid --idmap 2002:1002
.B # lctl nodemap_del_idmap --name remotesite --idtype projid --idmap 33:1
.B # lctl nodemap_add_idmap --name othersite --idtype uid --idmap 0-999:9000
.EE
.SH AVAILABILITY
.B lctl nodemap_del_idmap
is part of the
.BR lustre (7)
filesystem package since release 2.6.0
.\" Added in commit v2_5_56_0-14-g294b0efc31
.SH SEE ALSO
.BR lustre (7),
.BR lctl-nodemap-activate (8),
.BR lctl-nodemap-add (8),
.BR lctl-nodemap-add-idmap (8),
.BR lctl-nodemap-add-range (8),
.BR lctl-nodemap-del (8),
.BR lctl-nodemap-del-range (8),
.BR lctl-nodemap-modify (8)
