.TH LCTL-NODEMAP_DEL_RANGE 8 2024-08-14 Lustre "Lustre Configuration Utilities"
.SH NAME
lctl-nodemap_del_range \- delete an existing NID range from a nodemap
.SH SYNOPSIS
.SY "lctl nodemap_del_range"
.BI --name " NODEMAP_NAME"
.BI --range " NID_RANGE"
.YS
.SH DESCRIPTION
.B nodemap_del_range
deletes a NID range from a nodemap. Clients will be moved to the default
nodemap.
.SH OPTIONS
.TP
.BI --name " NODEMAP_NAME"
The name of the nodemap that this range should be deleted from.
.TP
.BI --range " NID_RANGE"
The NID range that should be deleted from the nodemap.
.SH EXAMPLES
.EX
.B # lctl nodemap_del_range --name remotesite --range 192.168.1.[1-254]@tcp
.B # lctl nodemap_del_range --name othersite --range 192.168.2.[1-254]@tcp
.EE
.SH AVAILABILITY
.B lctl nodemap_del_range
is part of the
.BR lustre (7)
filesystem package since release 2.6.0
.\" Added in commit v2_5_56_0-13-g4642f30970
.SH SEE ALSO
.BR lustre (7),
.BR lctl-nodemap-activate (8),
.BR lctl-nodemap-add (8),
.BR lctl-nodemap-add-idmap (8),
.BR lctl-nodemap-add-range (8),
.BR lctl-nodemap-del (8),
.BR lctl-nodemap-del-idmap (8),
.BR lctl-nodemap-modify (8)
