.TH LCTL-CHANGELOG_DEREGISTER 8 2024-08-13 Lustre "Lustre Configuration Utilities"
.SH NAME
lctl-changelog_deregister \- deregister existing changelog user
.SH SYNOPSIS
.SY lctl
.B --device
.I MDT_NAME
.B changelog_deregister
.RI [ ID |\c
.B cl\c
.IR ID ]
.RB [ --help | -h ]
.RB [ --user | -u
.IR USERNAME ]
.YS
.SH DESCRIPTION
This command is used to deregister an existing changelog user on selected
device. User can be deregistered by its
.I ID
or specific
.I USERNAME
used on registration.
.SH OPTIONS
.TP
.BR -h ", " --help
Output brief command usage help.
.TP
.BR -u ", " --user \fI USERNAME
Deregistration by username. If changelog user specified unique name during
registration then it can be deregistered by
.I USERNAME
instead of
.IR ID .
.SH EXAMPLES
Deregister changelog user on device
.B testfs-MDT0000
by
.RB ' cl\c
.IR ID ':
.RS
.EX
.B # lctl --device testfs-MDT0000 changelog_deregister cl1
testfs-MDT0000: Deregistered changelog user #1
.EE
.RE
.PP
Deregister changelog user by pure
.BR ID :
.RS
.EX
.B # lctl --device testfs-MDT0000 changelog_deregister 1
testfs-MDT0000: Deregistered changelog user #1
.EE
.RE
.PP
Deregister changelog user by its specific name
.BR testname :
.RS
.EX
.B # lctl --device testfs-MDT0000 changelog_deregister -u testname
testfs-MDT0000: Deregistered changelog user #1
.EE
.RE
.SH AVAILABILITY
.B lctl changelog_deregister
is a subcommand of
.BR lctl (8)
and is distributed as part of the
.BR lustre (7)
filesystem package since release 1.7.0
.\" Added in commit 1.6.0-2540-g2c74bfcb7a
.SH SEE ALSO
.BR lctl (8),
.BR lctl-changelog_register (8)
