.TH LCTL-LFSCK_STOP 8 "2017-05-13" Lustre "configuration utilities"
.SH NAME
lctl-lfsck_stop \- stop the online Lustre File System Check
.SH SYNOPSIS
.br
.B lctl lfsck_stop  \fR[-M | --device [MDT,OST]_device] [-A | --all] [-h | --help]
.br
.SH DESCRIPTION
Stop LFSCK on the specified MDT or OST device.
.SH OPTIONS
.TP
.B  -M, --device <[MDT,OST]_device>
The MDT or OST device to stop LFSCK/scrub on. If "-M" option is not specified,
it will select the available Lustre device on current server automatically.
But under the following cases you need to specify the device (see "-M" option)
explicitly: if there are multiple devices on current server those belong to
different Lustre filesystems, or if "-A" option is not specified and there are
multiple devices on current server.
.TP
.B  -A, --all
Stop LFSCK on all available devices in the system by single LFSCK command.
Such LFSCK command can be executed on any MDT deivce in the system.
.TP
.B  -h, --help
Show this help.

.SH AVAILABILITY
.B lctl-lfsck-stop
is part of the
.BR lustre (7)
filesystem package.
.SH SEE ALSO
.BR lctl (8),
.BR lctl-lfsck-start (8),
.BR lctl-lfsck-query (8)
