.TH LCTL-NODEMAP_SET_FILESET 8 2024-08-14 Lustre "Lustre Configuration Utilities"
.SH NAME
lctl-nodemap_set_fileset \- add a fileset to a nodemap
.SH SYNOPSIS
.SY "lctl nodemap_set_fileset"
.BI --name " NODEMAP"
.BI --fileset " SUBDIRECTORY"
.YS
.SH DESCRIPTION
.B nodemap_set_fileset
adds
.I FILESET
to the specified
.IR NODEMAP .
The
.I SUBDIRECTORY
must begin with '/'. Clients belonging to
.I NODEMAP
will be automatically
presented the corresponding
.I SUBDIRECTORY
when mounting.
This means these clients are doing an implicit subdirectory
mount on the subdirectory represented by the defined
.IR SUBDIRECTORY .
.SH OPTIONS
.TP
.BI --name " NODEMAP"
The name of the nodemap that this fileset should be associated with.
.TP
.BI --fileset " SUBDIRECTORY"
The fileset to restrict the clients to. The fileset must begin with '/'.
.SH EXAMPLES
.EX
.B # lctl nodemap_set_fileset --name tenant1 --fileset '/dir1'
.B # lctl nodemap_set_fileset --name admins --fileset ''
.EE
.SH AVAILABILITY
.B lctl nodemap_set_fileset
is part of the
.BR lustre (7)
filesystem package since release 2.9.0
.\" Added in commit v2_8_53_0-63-g25420c75e4
.SH SEE ALSO
.BR lustre (7),
.BR lctl-nodemap-activate (8),
.BR lctl-nodemap-add (8),
.BR lctl-nodemap-add-idmap (8),
.BR lctl-nodemap-add-range (8),
.BR lctl-nodemap-del (8),
.BR lctl-nodemap-del-idmap (8),
.BR lctl-nodemap-del-range (8),
.BR lctl-nodemap-modify (8)
