.TH LCTL-NODEMAP_ADD_IDMAP 8 "2015-01-20" Lustre "configuration utilities"
.SH NAME
lctl-nodemap_add_idmap \- define a range of NIDs for a nodemap
.SH SYNOPSIS
.br
.B lctl nodemap_add_idmap <--name name> <--idtype {uid|gid}>
<--idmap clientid:fsid>
.br
.SH DESCRIPTION
.B nodemap_add_idmap adds an identity mapping to a nodemap. Clients that are
members of the given nodemap will have the identities of their users mapped
accordingly.

.SH OPTIONS
.I name
is the name of the nodemap that this idmap should be added to.

.I idtype
is either "uid" or "gid" depending on if it is a user ID or group ID that is to
be mapped.

.I idmap
is the identity to map, and what it should be mapped to. The first digit is the
ID of the user or group as it is on the client, and the second number is the ID
that it should map to on the Lustre filesystem.

.SH EXAMPLES
.nf
# lctl nodemap_add_idmap --name remotesite --idtype uid --idmap 2001:1001
# lctl nodemap_add_idmap --name remotesite --idtype gid --idmap 2002:1002
.fi

.SH AVAILABILITY
.B lctl
is part of the
.BR Lustre (7)
filesystem package.
.SH SEE ALSO
.BR lustre (7),
.BR lctl-nodemap-activate (8),
.BR lctl-nodemap-add (8),
.BR lctl-nodemap-del (8),
.BR lctl-nodemap-add-range (8),
.BR lctl-nodemap-del-range (8),
.BR lctl-nodemap-del-idmap (8),
.BR lctl-nodemap-modify (8)
