.TH LFS-PROJECT 1 2025-01-24 "Lustre" "Lustre User Utilities"
.SH NAME
lfs-project \- Change or list project attribute for specified file or directory.
.SH SYNOPSIS
.SY "lfs project"
.RB [ -d | -r ]
.IR FILE | DIRECTORY ...
.SY "lfs project"
.RB { -p
.I ID
.RB | -s }
.RB [ -r ]
.IR FILE | DIRECTORY ...
.SY "lfs project"
.B -c
.RB [ -d | -r
.RB [ -p
.IR ID ]
.RB [ -0 ]]
.IR FILE | DIRECTORY ...
.SY "lfs project"
.B -C
.RB [ -d | -r ]
.RB [ -k ]
.IR FILE | DIRECTORY ...
.YS
.SH DESCRIPTION
.BR "lfs project"
.RB [ -d | -r ]
.IR FILE | DIRECTORY ...
.TP
List project ID and flags on file(s) or directories.
.TP
.B -d
Show the directory's own project ID and flags, override
.B -r
option.
.TP
.B -r
Recursively list all descendants'(of the directory) project attribute.
.PP
.BR "lfs project"
.BR { -p
.I ID
.RB | -s }
.RB [ -r ]
.IR FILE | DIRECTORY ...
.TP
Set project ID and/or inherit flag for specified file(s) or directories.
.TP
.BI -p \ ID
Set project
.I ID
with given value for the specified file or directory
.TP
.B -s
Set the
.B PROJID_INHERIT
attribute on directories, so that new files and subdirectories created
therein will inherit the project ID and attribute from the parent.
.TP
.B -r
Set project
.I ID
with the directory's project ID for all its descendants (with
.B -p
specified). For descendant directories, also set
inherit flag (if
.B -s
specified).
.PP
.BR "lfs project"
.B -c
.RB [ -d | -r [ -p
.IR ID ]
.RB [ -0 ]]
.IR FILE | DIRECTORY ...
.PP
Check project ID and flags on file(s) or directories, print outliers.
.TP
.B -c
Check project ID and inherit flag on specified file(s) or directory. If
.B -p
is not given, then use the project ID on the top-level directory,
otherwise use the ID specified with
.BR -p .
if checking a directory and or recursively, print only files that do not match.
.TP
.B -0
Print pathnames returned by -c with a trailing NUL, suitable for use by
.B 'xargs -0 lfs project -p'.
.PP
.BR "lfs project"
.B -C
.RB [ -d | -r ]
.RB [ -k ]
.IR FILE | DIRECTORY ...
.PP
Clear the project inherit flag and ID on the file(s) or directories
.TP
.B -C
Clear inherit attribute and reset project ID to 0 for file or directory.
.TP
.B -d
Clear only the directory itself.
.TP
.B -r
Clear the directory and all its descendants recursively. If neither
.B -d
nor
.B -r
is specified, clear the directory and its
immediate children.
.TP
.B -k
Keep the project ID unchanged.
.SH EXAMPLES
set directory quota on
.BR /mnt/lustre/dir1,
all descendants' project ID and inherit attribute are set:
.EX
.RS
.B $ lfs project -srp 1000 /mnt/lustre/dir1
.RE
.EE
.PP
Check directory
.BR /mnt/lustre/dir1,
whether all files and directories ID are 1000, inherit attribute
is properly set for all directories, print mismatch
if any are found:
.EX
.RS
.B $ lfs project -cr -p 1000 /mnt/lustre/dir1
.RE
.EE
.SH AVAILABILITY
.B lfs project
is part of the
.BR lustre (7)
filesystem package since release 1.4.0
.\" Added in commit 1.3.4-465-g761ab6a5cd
.SH SEE ALSO
.BR lfs (1),
.BR xargs (1)
