.TH LFS-QUOTA 1 2022-02-26 "Lustre" "Lustre Utilities"
.SH NAME
lfs-quota \- display quota limits and status for users, groups, or projects.
.SH SYNOPSIS
.BR "lfs quota " [ -q "] [" -v "] [" -h "] [" -o
.IR OBD_UUID | \fB-i
.IR MDT_IDX | \fB-I
.IR OST_IDX "] [" \fB-u
.IR USER | \fB-g
.IR GROUP | \fB-p
.IR PROJID "] [" \fB--pool
.IR OST_POOL_NAME "] [" MOUNT_POINT " ...]"

.br
.BR "lfs quota " [ -hq "] {" -U | -G | -P }
.RI [ MOUNT_POINT " ...]"
.br

.br
.BR "lfs quota " -t " {" -u | -g | -p }
.RI [ MOUNT_POINT " ...]"
.br

.br
.BR "lfs quota " -a " {" -u | -g | -p }
.RI [ MOUNT_POINT " ...]"
.br

.TP
.SH DESCRIPTION
.PP
.TP
.BR "lfs quota " [ \fIMOUNT_POINT " ...]"
Display disk usage and limits for individual users, groups, and projects for
each MOUNT_POINT.
An asterisk is displayed when the quota is exceeded.
By default the statistics for the entire filesystem are displayed but
individual MDTs and OSTs can be specified with the
.B --ost
or
.B --mdt
options.  A user, group, or project ID can be specified.
If user, group, and project are omitted, quotas for the
current uid/gid/projid are shown.
If no MOUNT_POINT is specified, quotas for all Lustre mountpoints will be shown.
.TP
.BR -h | --human-readable
This will change the formatting of
block storage and time values. Without this option block storage values
are in kilobytes and times are in seconds. With this option block storage
values use the common metric binary suffixes
.BR K ", " M ", " G ", " T ", " P ", and " E
which specify units of 2^10, 2^20, 2^30, 2^40, 2^50 and 2^60 bytes,
respectively.  Time values will use the "XXwXXdXXhXXmXXs" format, which
specifies weeks, days, hours, minutes, seconds.
.TP
.BR -g | --group " {" \fIGROUP | \fIGID }
Display quota information for group name \fIGROUP\fR or numeric \fIGID\fR.
.TP
.BR -m | --mdt " " \fIMDT_IDX
Display quota information for MDT \fIMDT_IDX\fR.
.TP
.BR -o | --ost " " \fIOST_IDX
Display quota information for OST \fIOST_IDX\fR.
.TP
.BR --pool " " \fIPOOL_NAME
Display quota information for OST pool \fIPOOL_NAME\fR.
.TP
.BR -p | --projid " " \fIPROJID
Display quota information for project \fIPROJID\fR.
.TP
.BR -q | --quiet
Display only the line containing the data.
The line saying what the data is, and the column headers will not be printed.
.TP
.BR -u | --user " {" \fIUSER \fR| \fIUID \fR}
Display quota information for user name
.I USER
or numeric
.IR UID .
Can be used without specifying the mount point to get quota information
from all filesystems for the specified
.IR USER | UID .
.TP
.BR -v | --verbose
Display per-MDT and per-OST statistics in addition
to the usual system wide data. An asterisk near the OST or MDT means that
the quota is exceeded only for that specific target. The user is over the
quota only if an asterisk is near the whole filesystem usage.
Inactive target will also be printed but marked as "inact".
.TP
.BR "lfs quota " { -U | -G | -P "} " MOUNT_POINT
Display default quota values for users, groups, or projects.
This command requires super user permissions.
.TP
.BR -G | --default-grp " {" \fIGROUP | \fIGID }
Display default quota limits for group name \fIGROUP\fR or numeric \fIGID\fR.
.TP
.BR -P \fIPROJID
Display default quota limits for project \fIPROJID\fR.
.TP
.BR -U | --default-usr " {" \fIUSER | UID }
Display default quota limits for username \fIUSER\fR or numeric \fIUID\fR.
.TP
.BR "lfs quota -a" " {" -u | -g | -p "} " \fIMOUNT_POINT
.TP
Display all quota setting for all users, groups, or projects.
.TP
.B "lfs quota -a -u"
.TP
Display all quota settings for all users across all mounted filesystems.
.TP
.BR "lfs quota -t" | --times " {" -u | -g | -p "} [" --pool " \fIPOOL_NAME\fR] " \fIMOUNT_POINT
Display grace times for users, groups, or projects.
Time values use the "XXwXXdXXhXXmXXs" format, which specifies
weeks, days, hours, minutes, seconds.
.SH EXAMPLES
.TP
.B $ lfs quota /mnt/lustre
Display quotas and usage for current user, group, and project
.TP
.B # lfs quota -u bob /mnt/lustre
Display quotas and usage for user 'bob'
.TP
.B # lfs quota -U /mnt/lustre
Display default user quotas
.TP
.B $ lfs quota -t -u /mnt/lustre
Display grace times for user quotas on /mnt/lustre
.TP
.B # lfs quota -u ivan --pool flash_pool /mnt/lustre
Display quotas and usage for user
.B ivan
from the OST pool
.BR flash_pool .
.TP
.B $ lfs quota -t -g --pool flash_pool /mnt/lustre
Display grace times for group quotas for the OST pool
.BR flash_pool .
.TP
.SH SEE ALSO
.BR lfs (1),
.BR lfs-setquota(1)
