.TH LFS-MIRROR-WRITE 1 2018-09-23 "Lustre" "Lustre Utilities"
.SH NAME
lfs mirror write \- write a mirror's content of a mirrored file
.SH SYNOPSIS
.B lfs mirror write
{\fB\-\-mirror-id|\-N\fR <\fImirror_id\fR>}
[\fB\-\-inputfile|\-i\fR <\fIinput_file\fR>]
<\fImirrored_file\fR>
.SH DESCRIPTION
This command writes the content of a file's mirror, the file is specified by the
path name \fImirrored_file\fR, the mirror is specified by its mirror ID
\fImirror_id\fR.
.SH OPTIONS
.TP
.BR \-\-mirror-id|\-N\fR\ <\fImirror_id\fR>
This option indicates the content of which mirror specified by \fImirror_id\fR
needs to be written. The \fImirror_id\fR is the numerical unique identifier for
a mirror.
.TP
.BR \-\-inputfile|\-i\fR\ <\fIinput_file\fR>
The path name of the input file, if not specified, the standard input stream
will be used. The input stream or input_file cannot be the same mirrored file
as the \fImirrored_file\fR. if you'd like to copy a mirror's content to
another mirror of the same mirrored file, use \fBlfs mirror copy\fR command.
.SH EXAMPLES
.TP
.B lfs mirror write --mirror-id 3 /mnt/lustre/file1 < /tmp/m2
Write the content of /mnt/m2 to the mirror with miro ID 3 for
/mnt/lustre/file1.
.TP
.B lfs mirror write -N2 -i /tmp/m2 /mnt/lustre/file1
Write the content of /mnt/m2 to the mirror with mirror ID 2 for
/mnt/lustre/file1.
.SH AUTHOR
The \fBlfs mirror write\fR command is part of the Lustre filesystem.
.SH SEE ALSO
.BR lfs (1),
.BR lfs-setstripe (1),
.BR lfs-getstripe (1),
.BR lfs-mirror-create (1),
.BR lfs-mirror-extend (1),
.BR lfs-mirror-split (1),
.BR lfs-mirror-verify (1),
.BR lfs-mirror-read (1)
.BR lfs-mirror-copy (1)
