.TH LFS-SETQUOTA 1 2017-07-21 "Lustre" "Lustre Utilities"
.SH NAME
lfs setquota \- set quota limits or grace time for users, groups or projects.
.SH SYNOPSIS
.B lfs setquota {\fB-u|--user|-g|--group|-p|--projid\fR} <\fIuname|uid|gname|gid|projid\fR>
       [\fB--block-softlimit|-b\fR <\fIblock-softlimit\fR>[kMGTPE]]
       [\fB--block-hardlimit|-B\fR <\fIblock-hardlimit\fR>[kMGTPE]]
       [\fB--inode-softlimit|-i\fR <\fIinode-softlimit\fR>[kMGTPE]]
       [\fB--inode-hardlimit|-I\fR <\fIinode-hardlimit\fR>[kMGTPE]] <\fIfilesystem\fR>
.TP
.B lfs setquota \fB-t\fR {\fB-u|-g|-p\fR}
       [\fB--block-grace|-b\fR <\fIblock-grace\fR>]
       [\fB--inode-grace|-i\fR <\fIinode-grace\fR>] <\fIfilesystem\fR>
.TP
.B lfs setquota {\fB-u|--user|-g|--group|-p|--projid\fR} <\fIuname|uid|gname|gid|projid\fR>
       [\fB--default|-d\fR] <\fIfilesystem\fR>
.TP
.B lfs setquota {\fB-U|--default-usr|-G|--default-grp|-P|--default-prj\fR}
       [\fB--block-softlimit|-b\fR <\fIblock-softlimit\fR>[kMGTPE]]
       [\fB--block-hardlimit|-B\fR <\fIblock-hardlimit\fR>[kMGTPE]]
       [\fB--inode-softlimit|-i\fR <\fIinode-softlimit\fR>[kMGTPE]]
       [\fB--inode-hardlimit|-I\fR <\fIinode-hardlimit\fR>[kMGTPE]] <\fIfilesystem\fR>
.TP
.SH DESCRIPTION
.PP
.BR "lfs setquota " {\fB-u|-g|-p\fR}
.TP
Command sets the filesystem quotas for users, groups or projects respectively. \
Block limits unit is kilobyte (1024) by default and block limits are always \
kilobyte-grained (even if specified in bytes), block limits can be specified \
with a \
.BR k "," M "," G "," T "," P ", or " E \
suffixes which specify units of 2^10, 2^20, 2^30, 2^40, 2^50 and 2^60 \
accordingly.
.TP
.B -u|--user <\fIuname|uid\fR>
Set user quota for \fIuname\fR or \fIuid\fR.
.TP
.B -g|--group <\fIgname|gid\fR>
Set group quota for name \fIgname\fR or \fIgid\fR.
.TP
.B -p|--project <\fIprojid\fR>
Set project quota for \fIprojid\fR.
.TP
.B -d|--default
Set user/group/project to use the default quota limits.
.TP
.B -b|--block-softlimit <\fIblock-softlimit\fR>
Specify block softlimit, zero means unlimited.
.TP
.B -B|--block-hardlimit <\fIblock-hardlimit\fR>
Specify block hardlimit, zero means unlimited. The block hardlimit should be \
greater than block softlimit when it's being specified.
.TP
.B -i|--inode-softlimit <\fIinode-softlimit\fR>
Specify inode softlimit, zero means unlimited.
.TP
.B -I|--inode-hardlimit <\fIinode-hardlimit\fR>
Specify inode hardlimit, zero means unlimited. The inode hardlimit should be \
greater than inode softlimit when it's being specified.
.PP
.BR "lfs setquota -t "
.TP
Command sets the filesystem quota grace time for users, groups, or projects. \
This is a global value that can take two forms: an amount of time or the word \
\'\fBnotify\fR'.  Traditionally, this indicates the amount of time in seconds \
that the soft quota limit can be exceeded before users are prevented from \
creating new files or consuming more space.  This is intended to allow users \
to exceed the quota limit for a short time to complete their work without \
having to grant each user a larger hard quota limit. The alternative value of \
\'\fBnotify\fR' informs users with an '\fB*\fR' in the quota output that they \
are nearing their hard quota limit but does not block new writes until the hard \
quota limit is reached.  The soft quota state is reset once the user, group, \
or project reduces their space usage or file count below the soft quota limit. \
Grace time is specified in "XXwXXdXXhXXmXXs" format or as an integer seconds \
value.  The maximum is 2^48 - 1 seconds.
.TP
.B -t
Set quota grace times.
.TP
.B -u
Set grace time for user.
.TP
.B -g
Set grace time for group.
.TP
.B -p
Set grace time for project.
.TP
.B -b|--block-grace 'notify'|<\fIblock-grace\fR>
Specify grace time for block quota.
.TP
.B -i|--inode-grace 'notify'|<\fIinode-grace\fR>
Specify grace time for inode quota.
.PP
.BR "lfs setquota " {\fB-U|--default-usr|-G|--default-grp|-P|--default-prj\fR}
.TP
Command sets the filesystem default limits for user,group,project quotas, \
if set, users/groups/projects without specific quota setting will use \
default quota limits automatically.
.TP
.B -U|--default-usr
Set default user quota limit.
.TP
.B -G|--default-grp
Set default group quota limit.
.TP
.B -P|--default-prj
Set default project quota limit.
.TP
.PP
.SH EXAMPLES
.TP
.B $ lfs setquota -u bob --block-softlimit 2G --block-hardlimit 1G /mnt/lustre
Set quotas of user `bob': 1GB block hardlimit and 2 GB block softlimit
.TP
.B $ lfs setquota -u bob -d /mnt/lustre
Set quotas of user `bob' to use default quota setting
.TP
.B $ lfs setquota -U --block-softlimit 1G --block-hardlimit 2G /mnt/lustre
Set system default user quota: 1 GB block softlimit and 2 GB block hardlimit
.TP
.B $ lfs setquota -t -u --block-grace 1000 --inode-grace 1w4d /mnt/lustre
Set grace times for user quotas: 1000 seconds for block quotas, 1 week and 4 \
days for inode quotas
.SH SEE ALSO
.BR lfs (1),
.BR lfs-quota(1)
