.TH LFS-MIRROR-EXTEND 1 2017-07-25 "Lustre" "Lustre Utilities"
.SH NAME
lfs-mirror-extend \- add mirror(s) to an existing file
.SH SYNOPSIS
.nh
.ad l
.B lfs mirror extend
[\fB\-\-no\-verify\fR]
[\fB\-\-mirror\-count\fR|\fB\-N\fR[\fIMIRROR_COUNT\fR]]
[\fB\-\-bandwidth\-limit\fR|\fB\-W\fR \fIBANDWIDTH\fR]
[\fB\-\-stats\fR|\fB\-\-stats\-interval\fR=\fISTATS_INTERVAL\fR]
[\fISETSTRIPE_OPTIONS\fR|\fB\-f\fR \fIVICTIM_FILE\fR]
\fIFILENAME\fR ...
.SH DESCRIPTION
This command adds mirror(s) to an existing file specified by the path name
\fIFILENAME\fR.
.br
The file \fIFILENAME\fR can already be a mirrored file, or just a regular
non-mirrored file. If it's a non-mirrored file, then the command will convert it
to a mirrored file.
.br
The \fB\-\-mirror\-count\fR|\fB\-N\fR option is optional and indicates how many
mirrors that have the same layout will be added. It can be repeated multiple
times to separate mirrors that have different layouts. The \fIMIRROR_COUNT\fR
argument is optional and defaults to 1 if it's not specified; if specified, it
must follow the option without a space. If \fB\-\-mirror\-count\fR|\fB\-N\fR is
not specified, the default value of 1 will be used.
.br
The \fISETSTRIPE_OPTIONS\fR specify the specific layout for the mirror. It can
be a plain layout with specific striping pattern or a composite layout like
Progressive File Layout (PFL) (see \fBlfs-setstripe\fR(1)).
If \fISETSTRIPE_OPTIONS\fR are not specified,
then the stripe options inherited from the previous component will be used.
If \fIVICTIM_FILE\fR exists, then the
command will merge the layout from that file as a mirror added to the
mirrored file. After the command is finished, the victim file will be
removed.  The \fISETSTRIPE_OPTIONS\fR cannot be specified with
\fB\-f\fR \fIVICTIM_FILE\fR option in one command line.
.br
If \fIVICTIM_FILE\fR is specified, the utility will verify that the file contents
from \fIVICTIM_FILE\fR are the same as \fIFILENAME\fR. Otherwise the command
will return failure. However, option \fB\-\-no\-verify\fR can be used to
override this verification. The option can save significant time on file
comparison if the file size is large, but use it only when the file contents
are known to be the same.
.br
If no option is specified, then the command will return an error.
.SH OPTIONS
.TP
.BR \-\-mirror\-count\fR|\fB\-N\fR[\fIMIRROR_COUNT\fR]
The number of mirrors that have the same layout to be added. The option can be
repeated multiple times to separate mirrors that have different layouts. The
\fIMIRROR_COUNT\fR argument is optional and defaults to 1 if it's not specified;
if specified, it must follow the option without a space.
.TP
.I SETSTRIPE_OPTIONS
The layout of one mirror. The options are the same as those for
\fBlfs-setstripe\fR(1) command.
If \fISETSTRIPE_OPTIONS\fR are not specified, then the stripe options inherited
from the previous component will be used. This option cannot be specified with
\fB\-f\fR \fIVICTIM_FILE\fR option.
.TP
.BR \-f\fR\ \fIVICTIM_FILE\fR
The layout of \fIVICTIM_FILE\fR will be merged as a mirror added to the
mirrored file. This option cannot be specified with \fISETSTRIPE_OPTIONS\fR
option.
.TP
.BR \-\-no\-verify
This option indicates not to verify the mirror(s) from victim file(s) in case
the victim file(s) contains the same data as the original mirrored file.
.TP
.BR \-\-stats
This option enables progress updates every 5 seconds, in YAML format.
.TP
.BR \-\-stats-interval=\fISTATS_INTERVAL
This option enables progress updates every \fISTATS_INTERVAL\fR seconds, in YAML format.
.TP
.BR \-\-bandwidth\-limit\fR|\fB\-W\fR\fIBANDWIDTH\fR
This option enables throttling so that mirror extending writes no more than
\fIBANDWIDTH\fR bytes a second.  An optional suffix can be used to
specify the units in
.BR K ilobytes,
.BR M egabytes
or
.BR  G igabytes.
.SH EXAMPLES
.TP
.B lfs mirror extend -N2 /mnt/lustre/file1
Add 2 mirrors to /mnt/lustre/file1. If file1 is a non-mirrored file, then the
command will convert it to a mirrored file first and then add mirrors. Each
mirror has the same default striping pattern with \fIstripe_count\fR and
\fIstripe_size\fR inherited from filesystem-wide default values, and
OST \fIpool_name\fR inherited from parent directory.
.LP
.B lfs mirror extend -N3 -E 1M -c 1 -E 32M -c 4 -S 16M -E eof -c -1
.B /mnt/lustre/file1
.in
Add 3 PFL mirrors to /mnt/lustre/file1. Each mirror has the same specified PFL
layout.
.LP
.B lfs mirror extend -N -c 1 -S 4M -N -c 2 -o 2,3 -p flash
.B -N -p none /mnt/lustre/file1
.in
Add 3 plain layout mirrors to /mnt/lustre/file1. The first mirror has a single
stripe and 4MB stripe size. The second mirror has two stripes and locates on
OSTs with indices 2 and 3 allocated from the \fBflash\fR OST pool.
It also has 4MB stripe size inherited from the first mirror.
The third mirror has two stripes and 4MB stripe size inherited from the previous
mirror, and also has inherited OST \fIpool_name\fR from parent directory.
.LP
.B lfs mirror extend -N2 -E 4M -c 2 --pool flash -E eof -c 4 -N3 -E 16M -c 4
.B -S 16M --pool archive -E eof -c -1 /mnt/lustre/file1
.in
Add 5 PFL mirrors to /mnt/lustre/file1. The first and second mirrors have the
same PFL layout. All of the components are allocated from the flash OST pool.
The last three mirrors have the same PFL layout. All of these components have a
stripe size of 16MB and use OSTs in the archive pool.
.LP
.B lfs mirror extend --no-verify -N -f /mnt/lustre/file2 -N -f /mnt/lustre/file3
.B /mnt/lustre/file1
.in
Merge the layouts from /mnt/lustre/file2 and /mnt/lustre/file3, which contain
the same data as /mnt/lustre/file1, use the layouts as mirrors and add them to
/mnt/lustre/file1 without verification.
.SH AUTHOR
The \fBlfs mirror extend\fR command is part of the Lustre filesystem.
.SH SEE ALSO
.BR lfs (1),
.BR lfs-setstripe (1),
.BR lfs-mirror-create (1),
.BR lfs-mirror-delete (1),
.BR lfs-mirror-split (1),
.BR lfs-mirror-resync (1),
.BR lfs-mirror-verify (1)
