.TH lfs 1 "2018-01-24" Lustre "user utilities"
.SH NAME
lfs \- client utility for Lustre-specific file layout and other attributes
.SH SYNOPSIS
.br
.B lfs changelog \fR[\fB--follow\fR] <\fImdtname\fR> [\fIstartrec \fR[\fIendrec\fR]]
.br
.B lfs changelog_clear <\fImdtname\fR> <\fIid\fR> <\fIendrec\fR>
.br
.B lfs check \fR<\fBmgts\fR|\fBmdts\fR|\fBosts\fR|\fBall\fR>
.br
.B lfs data_version \fR[\fB-nrw\fR] \fB<\fIfilename\fR>
.br
.B lfs df \fR[\fB-ihlv\fR] [\fB--pool\fR|\fB-p \fR<\fIfsname\fR>[.<\fIpool\fR>]] [\fIpath\fR]
.br
.B lfs fid2path \fR[\fB--link \fR<\fIlinkno\fR>] <\fIfsname\fR|\fIrootpath\fR> <fid\fR> ...
.br
.B lfs find \fR<\fIdirectory\fR|\fIfilename \fR...>
      [[\fB!\fR] \fB--atime\fR|\fB-A\fR [\fB-+\fR]\fIn\fR]
[[\fB!\fR] \fB--ctime\fR|\fB-C\fR [\fB+-\fR]\fIn\fR]
      [[\fB!\fR] \fB--mtime\fR|\fB-M\fR [\fB-+\fR]\fIn\fR]
      [[\fB!\fR] \fB--component-count\fR|\fB--comp-count\fR [\fB+-\fR]\fIn\fR]
      [[\fB!\fR] \fB--component-flags\fR|\fB--comp-flags\fR <[\fB^\fR]\fIflag\fB,\fR...>]
      [[\fB!\fR] \fB--component-end\fR|\fB--comp-end\fR|\fB-E\fR [\fB+-\fR]\fIn\fR[\fBKMGTPE\fR]]
      [[\fB!\fR] \fB--component-start\fR|\fB--comp-start\fR [\fB+-\fR]\fIn\fR[\fBKMGTPE\fR]]
      [[\fB!\fR] \fB--mirror-count\fR|\fB-N\fR [\fB+-\fR]\fIn\fR]
      [[\fB!\fR] \fB--mirror-state\fR <[^]\fIstate\fR>]
      [[\fB!\fR] \fB--gid\fR|\fB-g\fR|\fB--group\fR|\fB-G\fR <\fIgname\fR>|<\fIgid\fR>]
      [[\fB!\fR] \fB--layout\fR|\fB-L mdt\fR,\fBraid0\fR,\fBreleased\fR]
[\fB--maxdepth\fR|\fB-D\fI n\fR]
      [[\fB!\fR] \fB--mdt\fR|\fB--mdt-index\fR|\fB-m\fR <\fIuuid\fR|\fIindex\fR,...>]
      [[\fB!\fR] \fB--mdt-count\fR|\fB-T\fR [\fB+-\fR]\fIn\fR]
[[\fB!\fR] \fB--mdt-hash\fR|\fB-H \fI<hashtype>\fR]
      [[\fB!\fR] \fB--name\fR|\fB-n \fI<pattern>\fR]
[[\fB!\fR] \fB--ost\fR|\fB-O\fR <\fIuuid\fR|\fIindex\fR,...>]
      [[\fB!\fR] \fB--pool\fR <\fIpool\fR>]
[\fB--print\fR|\fB-P\fR] [\fB--print0\fR|\fB-0\fR]
      [[\fB!\fR] \fB--projid\fR |<\fIprojid\fR>]
[[\fB!\fR] \fB--size|\fB-s\fR [\fB-+\fR]\fIn\fR[\fBKMGTPE\fR]]
      [[\fB!\fR] \fB--stripe-count\fR|\fB-c\fR [\fB+-\fR]\fIn\fR]
      [[\fB!\fR] \fB--stripe-index\fR|\fB-i\fR \fIn\fR,...]
      [[\fB!\fR] \fB--extension-size\fR|\fB-ext-size\fR|\fB-z\fR [\fB+-\fR]\fIn\fR[\fBKMG\fR]]
      [[\fB!\fR] \fB--stripe-size\fR|\fB-S\fR [\fB+-\fR]\fIn\fR[\fBKMG\fR]]
[[\fB!\fR] \fB--type\fR|\fB-t\fR {\fBbcdflps\fR}]
      [[\fB!\fR] \fB--uid\fR|\fB-u\fR|\fB--user\fR|\fB-U
\fR<\fIuname\fR>|<\fIuid\fR>]
.br
.B lfs flushctx
.RB [ --help | -h "] [" -k "] [" -r "] [" \fIrootpath\fR "]"
.br
.B lfs getname
.RB [ --help | -h "] [" --instance | -i "] [" --fsname | -n "] ["
.IR path ...]
.br
.B lfs getstripe
[\fB--component-count\fR|\fB--comp-count\fR]
        [\fB--component-end\fR|\fB-E\fR[=[\fB+-\fR]\fIN\fR[\fBKMGTPE\fR]]
        [\fB--component-flags\fR[=[\fB^\fR]\fIflag\fB,\fR...]]
        [\fB--component-id\fR|\fB-I \fR[=\fIcomp_id\fR]]
        [\fB--component-start\fR[=[\fB+-\fR]\fIN\fR[\fBKMGTPE\fR]]]
        [\fB--directory\fR|\fB-d\fR]
[\fB--fid\fR|\fB-F\fR]
[\fB--generation\fR|\fB-g\fR]
        [\fB--layout\fR|\fB-L\fR]
[\fB--mdt\fR|\fB--mdt-index\fR|\fB-m\fR]
[\fB--ost\fR|\fB-O\fR <\fIuuid\fR>]
        [\fB--pool\fR|\fB-p\fR]
[\fB--quiet\fR|\fB-q\fR]
[\fB--recursive\fR|\fB-r\fR]
        [\fB--raw\fR|\fB-R\fR]
[\fB--stripe-count\fR|\fB-c\fR]
[\fB--stripe-index\fR|\fB-i\fR]
        [\fB--stripe-size\fR|\fB-S\fR]
[\fB--extension-size\fR|\fB--ext-size\fR|\fB-z\fR]
        [\fB--verbose\fR|\fB-v\fR]
[\fB--yaml\fR|\fB-y\fR]
        <\fIdirname\fR|\fIfilename\fR> ...
.br
.B lfs migrate \fR{\fB--mdt-index\fR|\fB-m\fR} <\fImdt_index\fR> \fIdirectory\fR
.br
.B lfs migrate \fR[\fB--stripe-count\fR|\fB-c\fR \fR<\fIstripe_count\fR>]
            [\fB--stripe-index\fR|\fB-i\fR \fR<\fIstart_ost_idx\fR>]
            [\fB--stripe-size\fR|\fB-S\fR \fR<\fIstripe_size\fR>]
[\fB--pool\fR|\fB-p\fR \fR<\fIpool_name\fR>]
            [\fB-o\fR|\fB--ost-list \fR<\fIost_indices\fR>]
[\fB--block\fR|\fB-b\fR]
            [\fB--non-block\fR|\fB-n\fR] <\fIfile\fR|\fIdirectory\fR>
.br
.B lfs migrate \fR<\fB--component-end\fR|\fB-E\fR \fIcomp_end1\fR>
[\fISTRIPE_OPTIONS\fR]
            <\fB--component-end\fR|\fB-E\fR \fIcomp_end2\fR>
[\fISTRIPE_OPTIONS\fR]
            ... \fIfilename\fR
.br
.B lfs mkdir \fR[\fB-c\fR|\fB--count \fR<\fIstripe_count\fR>]
[\fB-i\fR|\fB--index \fR<\fImdt_idx\fR>]
          [\fB-h\fR|\fB--hash-type \fR<\fIhash_name\fR>]
[\fB-m\fR|\fB--mode \fR<\fImode\fR>]
          [\fB-D\fR|\fB--default\fR] \fIdirectory\fR
.br
.B lfs osts \fR[<\fIpath\fR>]
.br
.B lfs mdts \fR[<\fIpath\fR>]
.br
.B lfs path2fid \fR[\fB--parents\fR] <\fIpath\fR> ...
.br
.B lfs pool_list \fR<\fIfilesystem\fR>[\fB.\fR<\fIpool\fR>] | <\fIpathname\fR>
.br
.B lfs setstripe \fR[\fB--stripe-size\fR|\fB-S <\fIsize\fR>] [\fB--stripe-count\fR|-c <\fIcount\fR>]
        [\fB--stripe-index\fR|\fB-i <\fIstart_ost_index\fR>] [\fB--pool\fR|\fB-p \fR<\fIpoolname\fR>]
        [\fB--extension-size\fR|\fB--ext-size\fR|\fB-z <\fIext_size\fR>]
        [\fB--ost-list\fR|\fB-o <\fIost_indices\fR>] <\fIdirectory\fR|\fIfilename\fR>
.br
.B lfs setstripe -d \fR<\fIdir\fR>
.br
.B lfs setstripe --component-end\fR|\fB-E <\fIend1> [\fISTRIPE_OPTIONS\fR]
             [\fB--component-end\fR|\fB-E \fR<\fIend2\fR> [\fISTRIPE_OPTIONS\fR]]
             ... <\fIfilename>\fR
.br
.B lfs setstripe --component-add \fB-E\fR <\fIend1> [\fISTRIPE_OPTIONS]
             [\fB--component-end\fR|\fB-E \fR<\fIend2\fR> [\fISTRIPE_OPTIONS\fR]]
             ... <\fIfilename\fR>
.br
.B lfs setstripe --component-del \fR{\fB--component-id\fR|\fB-I \fR<\fIid\fR> |
                               \fB--component-flags \fR<\fIflags\fR>}
<\fIfilename\fR>
.br
.B lfs setstripe --yaml=\fR<\fIyaml_template_file\fR> <\fIfilename\fR>
.br
.B lfs unlink_foreign
.IR path \fR[\fIpath\fR ...]
.br
.B lfs --version
.br
.B lfs --list-commands
.br
.B lfs help
.SH DESCRIPTION
.B lfs
can be used to create a new file with a specific striping pattern, determine
the default striping pattern, gather the extended attributes (object numbers
and location) for a specific file. It can be invoked interactively without any
arguments or in a non-interactive mode with one of the arguments supported.
.SH COMMANDS
A number of sub-commands supported by lfs are listed below.  Other commands
are described in separate man pages of the form
.BI lfs- command
as listed in the
.B SEE ALSO
section at the end.
.TP
.B changelog
Show the metadata changes on an MDT.  Start and end points are optional.  The --follow option will block on new changes; this option is only valid when run direclty on the MDT node.
.TP
.B changelog_clear
Indicate that changelog records previous to <endrec> are no longer of
interest to a particular consumer <id>, potentially allowing the MDT to
free up disk space. An <endrec> of 0 indicates the current last record.
Changelog consumers must be registered on the MDT node using \fBlctl\fR.
.TP
.B check <mgts|mdts|osts|all>
Display the status of the MGTs, MDTs or OSTs (as specified in the command) or
all the servers (MGTs, MDTs and OSTs).
.TP
.B data_version [-nrw] <filename>
Display the current version of file data. If -n is specified, the data version
is read without taking a lock. As a consequence, the data version could be
outdated if there are dirty caches on filesystem clients, but this option will
not force data flushes and has less of an impact on the filesystem. If -r is
specified, the data version is read after dirty pages on clients are flushed. If
-w is specified, the data version is read after all caching pages on clients are
flushed.

Even with -r or -w, race conditions are possible and the data version should be
checked before and after an operation to be confident the data did not change
during it.

The data version is the sum of the last committed transaction numbers of all
data objects of a file. It is used by HSM policy engines for verifying that file
data has not been changed during an archive operation or before a release
operation, and by OST migration, primarily for verifying that file data has not
been changed during a data copy, when done in non-blocking mode.
.TP
.B flushctx
See lfs-flushctx(1).
.TP
.B osts
.RB [ path ]
List all the OSTs for all mounted filesystems. If a \fBpath\fR is provided
that is located on a lustre mounted file system then only the OSTs belonging
to that filesystem are displayed.
.TP
.B pool_list
.RI { filesystem }[ .poolname "] | {" pathname }
List the pools in
.I filesystem
or
.IR pathname ,
or the OSTs in
.IR filesystem.pool .
.TP
.B swap_layouts <filename1> <filename2>
Swap the data (layout and OST objects) of two regular files. The
two files have to be in the same filesystem, owned by the same user,
reside on the same MDT and writable by the user.

Swapping the layout of two directories is not permitted.
.TP
.B mkdir
lfs mkdir is documented in the man page: lfs-mkdir(1). NOTE:
.B lfs setdirstripe
is an alias of the command
.B lfs mkdir
.TP
.B mv
lfs mv is deprecated, use lfs
.B migrate
instead.
.TP
.B migrate
See lfs-migrate(1).
.TP
.B setstripe
See lfs-setstripe(1).
.TP
.B unlink_foreign
Remove the foreign files/dirs that are prevented to be using regular unlink/rmdir commands/syscalls. Works also for regular files/dirs.
.TP
.B --version
Output the build version of the lfs utility. Use "lctl lustre_build_version" to get the version of the Lustre kernel modules
.TP
.B --list-commands
Output a list of the commands supported by the lfs utility
.TP
.B help
Provides brief help on the various arguments
.TP
.B exit/quit
Quit the interactive lfs session
.SH EXAMPLES
.TP
.B $ lfs check all
Check the status of all servers (MGT, MDT, OST)
.TP
.B $ lfs osts
List all the OSTs
.TP
.B $ lfs mdts
List all the MDTs
.TP
.B $ lfs quotaoff -ug /mnt/lustre
Turn quotas of user and group off
.SH NOTES
The usage of \fBlfs find\fR, \fBlfs getstripe\fR, \fBlfs hsm_*\fR,
\fBlfs setstripe\fR, \fBlfs migrate\fR, \fBlfs getdirstripe\fR,
\fBlfs setdirstripe\fR, \fBlfs mkdir\fR, \fBlfs flushctx\fR
and \fBlfs project\fR are explained in separate man pages.
.SH AUTHOR
The lfs command is part of the Lustre filesystem.
.SH SEE ALSO
.BR lctl (8),
.BR lfs-df (1),
.BR lfs-fid2path (1),
.BR lfs-find (1),
.BR lfs-flushctx (1),
.BR lfs-getdirstripe (1),
.BR lfs-getname (1),
.BR lfs-getstripe (1),
.BR lfs-hsm (1),
.BR lfs-mkdir (1),
.BR lfs-migrate (1),
.BR lfs_migrate (1),
.BR lfs-project (1),
.BR lfs-path2fid (1),
.BR lfs-quota (1),
.BR lfs-setdirstripe (1),
.BR lfs-setquota (1),
.BR lfs-setstripe (1),
.BR lfs-pcc (1),
.BR lustre (7)
