.TH lfs_migrate 1 "Jul 21, 2010" Lustre "utilities"
.SH NAME
.B lfs_migrate
\- simple tool to migrate files between Lustre OSTs
.SH SYNOPSIS
.B lfs_migrate
.RB [ -c <stripe_count> ]
.RB [ -h ]
.RB [ -l ]
.RB [ -n ]
.RB [ -q ]
.RB [ -R ]
.RB [ -s ]
.RB [ -y ]
.RI [ file | "directory ..." ]
.br
.SH DESCRIPTION
.B lfs_migrate
is a simple tool to assist migration of files between Lustre OSTs.  It
is simply copying each specified file to a new file, verifying the file
contents have not changed, and then renaming the new file back to the
original filename.  This allows balancing space usage between OSTs, moving
files off OSTs that are starting to show hardware problems (though are still
functional), or OSTs that will be removed from the filesystem.
.PP
Because
.B lfs_migrate
is
.B not
yet closely integrated with the MDS, it cannot determine whether a file
is currently open and/or in-use by other applications or nodes.  That makes
it
.B
UNSAFE
for use on files that might be modified by other applications, since the
migrated file is only a copy of the current file, and this will result in
the old file becoming an open-unlinked file and any modifications to that
file will be lost.
.PP
Files to be migrated can be specified as command-line arguments.  If a
directory is specified on the command-line then all files within that
directory are migrated.  If no files are specified on the command-line,
then a list of files is read from the standard input, making
.B lfs_migrate
suitable for use with
.BR lfs (1) " find"
to locate files on specific OSTs and/or matching other file attributes.
.PP
The current file allocation policies on MDS dictate where the new files
are placed, taking into account whether specific OSTs have been disabled
on the MDS via
.BR lctl (8)
(preventing new files from being allocated there), whether
some OSTs are overly full (reducing the number of files placed on those
OSTs), or if there is a specific default file striping for the target
directory (potentially changing the stripe count, stripe size, OST pool,
or OST index of a new file).
.SH OPTIONS
.TP
.B \\-c <stripe_count>
Restripe file using the specified stripe count. This option may not be
specified at the same time as the -R option.
.TP
.B \\-h
Display help information.
.TP
.B \\-l
Migrate files with hard links (skip by default).  Files with multiple
hard links will be split into multiple separate files by
.B lfs_migrate
so they are skipped by default to avoid breaking the hard links.
.TP
.B \\-n
Only print the names of files to be migrated
.TP
.B \\-q
Run quietly (don't print filenames or status)
.TP
.B \\-R
Restripe file using default directory striping instead of keeping striping.
This option may not be specified at the same time as the -c option.
.TP
.B \\-s
skip file data comparison after migrate.  Default is to compare migrated file
against original to verify correctness.
.TP
.B \\-y
Answer 'y' to usage warning without prompting (for scripts, use with caution).
.SH EXAMPLES
To rebalance all files within
.I /testfs/jobs/2011
(which are known not to be modified by in-use programs):
.IP
lfs_migrate /testfs/jobs/2011
.PP
To migrate files within the
.I /testfs
filesystem on OST0004 (perhaps because it is much more full than other OSTs),
larger than 4GB (because it is more efficient to just migrate large files),
and older than two days (to avoid files that are in use, though this is NOT
a guarantee the files are not being modified, that is workload specific):
.IP
lfs find /testfs -obd test-OST0004 -size +4G -mtime +2d |
    lfs_migrate -y
.SH KNOWN BUGS
Hard links could be handled correctly in Lustre 2.0 by using
.BR lfs (1) " fid2path" .
.PP
Eventually, this functionality will be integrated into
.BR lfs (1)
itself and will integrate with the MDS layout locking to make it safe
in the presence of opened files and ongoing file IO.
.SH AVAILABILITY
.B lfs_migrate
is part of the 
.BR Lustre (7) 
filesystem package.  Added in the 1.8.4 release.
.SH SEE ALSO
.BR lfs (1)
