.TH liblustreapi 7 "2009 Aug 10" Lustre liblustreapi
.SH NAME
liblustre \- The liblustre library
.SH DESCRIPTION
The liblustre library provides functions to access and/or modify settings specific to the Lustre filesystem (allocation policies, quotas, etc).
.SH "SEE ALSO"
.BR lustre (7),
.BR llapi_file_create (3),
.BR llapi_file_open (3),
.BR llapi_file_get_stripe (3),
.BR llapi_quotactl (3)
