.TH ll_recover_lost_found_objs 1 "Aug 21, 2008" Lustre "utilities"
.SH NAME
ll_recover_lost_found_objs \- recover Lustre OST objects from lost+found
.SH SYNOPSIS
.B "ll_recover_lost_found_objs [-hnv] -d scan_directory"
.br
.SH DESCRIPTION
.B ll_recover_lost_found_objs
recovers objects from lost+found that might result from a
Lustre OST with a corrupted directory. Running e2fsck will fix the
directory, but puts all of the objects into lost+found, where they are
inaccessible to Lustre.
.TP
.I "\-d scan_directory"
Specify directory that will be scanned.  Normally this is the
.RB ' lost+found '
directory of an OST.
.TP
.I "\-h"
Print help message.
.TP
.I "\-n"
Run in non-fixing (dry-run) mode to report what would be fixed, but
do not actually modify the filesystem.  If the
.I scan_directory
is specified as the OST object directory (i.e.
.RB ' O ' )
then the existing OST objects can be scanned to verify and repair
their location in the object directory.
.TP
.I "\-v"
Increase verbosity.
.SH EXAMPLE
.fi
ll_recover_lost_found_objs -d /mnt/ost/lost+found
.SH SEE ALSO
.BR lustre (7),
.BR ll_decode_filter_fid (8)
