.TH llapi_pcc_clear 3 "2019 June 20" "Lustre User API"
.SH NAME
llapi_pcc_clear \- Remove all PCC backends from a client
.SH SYNOPSIS
.nf
.B #include <lustre/lustreapi.h>
.PP
.BI "int llapi_pcc_clear(const char *" mntpath ,
.BI "                    enum lu_pcc_cleanup_flags " flags );
.fi
.SH DESCRIPTION
.PP
The function
.BR llapi_pcc_clear()
deletes all PCC backends on the client with the mount point referenced by
.IR mntpath .
Refer to
.BR llapi_pcc_del()
for the usage of the input parameter
.IR flags .
.SH RETURN VALUES
.PP
.B llapi_pcc_clear()
returns 0 on success or a negative errno on failure.
.SH ERRORS
.TP 15
.SM -ENOMEM
Insufficient memory to complete operation.
.TP
.SM -EFAULT
Memory region is not properly mapped.
.TP
.SM -EINVAL
One or more invalid arguments are given.
.TP
.SM -EOPNOTSUPP
PCC backend operation is not supported.
.SH "SEE ALSO"
.BR llapi_pcc_del (3),
.BR lustreapi (7)
