.TH llapi_layout_file_comp_del 3 "2015 Nov 4" "Lustre User API"
.SH NAME
llapi_layout_file_comp_del \- delete the specified layout component
from an existing file.
.SH SYNOPSIS
.nf
.B #include <lustre/lustreapi.h>
.PP
.BI "int llapi_layout_file_comp_del(const char *" path ",
.BI "                               uint32_t "id ", uint32_t "flags );
.fi
.SH DESCRIPTION
.PP
Deletes the layout component(s) specified by
.I id
or
.I flags
from an existing file. The
.I id
must be a real unique component ID, when
.I flags
is specified,
.I id
must be set to zero.
Available
.IR flags
are:
.PP
.BR LCME_FL_INIT:
Instantiated components in the layout.
.PP
.BR LCME_FL_NEG|LCME_FL_INIT:
Uninstantiated components in the layout.
.SH RETURN VALUES
Returns 0 on success, or -1 if an error occurred (in which case, errno is
set appropriately).
.SH ERRORS
.TP 15
.SM EINVAL
An invalid argument was specified.
.TP
.SM ENOENT
.I path
doesn't exist or the specified component isn't found in file.
.SH "SEE ALSO"
.BR llapi_layout_alloc (3),
.BR llapi_layout_file_open (3),
.BR llapi_layout_get_by_path (3),
.BR llapi_layout_file_comp_add (3),
.BR llapi_layout_comp_id_get (3),
.BR llapi_layout_comp_use_id (3),
.BR llapi_layout (7),
.BR lustreapi (7)
