.TH llobdstat 1 "Jul 7, 2008" Lustre "utilities"
.SH NAME
llobdstat \- display OST statistics
.SH SYNOPSIS
.B "llobdstat ost_name [interval]"
.br
.SH DESCRIPTION
.B llobdstat
displays a line of OST statistics for the given
.I ost_name
every
.I interval
seconds.  It should be run directly on an OSS node.
Type control-C to stop statistics printing.
.SH EXAMPLE
.nf
# llobdstat liane-OST0002 1
/usr/bin/llobdstat on liane-OST0002
Processor counters run at 2800.189 MHz
Read: 1.21431e+07, Write: 9.93363e+08, create/destroy: 24/1499, stat: 34, punch: 18
[NOTE: cx: create, dx: destroy, st: statfs, pu: punch ]

Timestamp   Read-delta  ReadRate  Write-delta  WriteRate
--------------------------------------------------------
1217026053    0.00MB    0.00MB/s     0.00MB    0.00MB/s
1217026054    0.00MB    0.00MB/s     0.00MB    0.00MB/s
1217026055    0.00MB    0.00MB/s     0.00MB    0.00MB/s
1217026056    0.00MB    0.00MB/s     0.00MB    0.00MB/s
1217026057    0.00MB    0.00MB/s     0.00MB    0.00MB/s
1217026058    0.00MB    0.00MB/s     0.00MB    0.00MB/s
1217026059    0.00MB    0.00MB/s     0.00MB    0.00MB/s st:1
...
.fi
