.TH lmc 1 "2003 Oct 8" Lustre "configuration utilities"
.SH NAME
lmc \- Lustre configuration maker
.SH SYNOPSIS
.br
.B lmc
[options] --add <objecttype> [args]
.br
.SH DESCRIPTION
.B lmc 
, when invoked, adds configuration data to a configuration file. In future, 
lmc will also be able to remove configuration data or convert its format. 
A Lustre cluster consists of several components - MDSs, client mount-points, 
OSTs, LOVs and networks. A single configuration file would be generated for the complete cluster. In the lmc command line interface, each of these components is associated with an objecttype.
.PP
The objecttype refers to a collection of related configuration entities and can be one of 
.B net
,
.B MDS
,
.B LOV
,
.B OST
,
.B mtpt
,
.B route
or
.B echo-client.
.PP
We describe the arguments required for the addition of each objecttype. 
.PP
To generate configuration data associated with systems in a Lustre cluster:
.PP
.B --add node 
Adds a new node in the cluster configuration.
The arguements required are:
.TP 
--node <node_name>
This will create a new node with the given name if not already present.
.TP
--timeout <num>
Timeout before going into recovery
.TP
--lustre_upcall <path> 
Set the location of the Lustre upcall scripts used by the client for recovery
.TP
--portals_upcall <path> 
Specify the location of the Portals upcall scripts used by the client for recovery
.TP
--upcall <path> 
Specify the location of both (Lustre and Portals) upcall scripts used by the client for recovery
.PP
.B --add net 
Adds a network device descriptor for the given node, with parameters as indicated.
The arguments required are:
.TP 12
--node <node_name>
This will create a new node with the given name if not already present. This is also used to specify a specific node for other elements.
.TP
--nettype <type> 
This can be tcp, elan, gm, scimac.
.TP
--nid nid 
The network id, e.g. ElanID or IP address as used by Portals. If nid is '*', then the local address of the interface with specified nettype is will be substituted when the node is configured with lconf. An nid of '*' should be used only for the generic client configuration.
.TP
--hostaddr addr
.TP
--router 
Optional flag to mark this node as a router
.TP
--port [port] 
Optional arguement to indicate the tcp port. The default is 988. 
.TP
--tcpbuf <size> 
Optional arguement. The default TCP buffer size is 1MB.
.TP
--irq_affinity 0|1 
Optional arguement. Default is 0.
.TP
--nid_exchange 0|1 
Optional arguement since some OSTs might not have the required support. This is turned off by default, value of 1 will turn it ON. 
.PP
.B --add mds
Specify the MDS configuration
.TP
--node <node name> 
Name of the node on which the MDS resides
.TP
--mds <mds_name> 
Common name of the MDS
.TP 
--dev <pathname> 
Path of device on local system. If the is a file, then a loop device is created and used as the block device.
.TP
--size <size> 
Optional argument indicating the size (in KB) of the device to be created (used typically for loop devices).
.TP
--node <nodename> 
Adds an MDS to the specified node. This requires a --node argument, and it must not be a profile node.
.TP
--fstype extN|ext3 
Optional argument used to specify the file system type. Default is ext3.
.TP
--journal_size <size> 
Optional arguement to specify the journal size for the ext2/ext3 file system. The size should be in the units expected by mkfs, so for ext3 it should be in MB. If this is option is not used, the ext2/ext3 filesystem will be configured with the default journal size.
.PP
.B --add lov 
Creates an LOV with the specified parameters. The mds_name must already exist in the descriptor.
.TP
--lov <name>
Common name for the LOV
.TP
--mds <name>
Common name for the MDS
.TP
--stripe_sz <size>
Stripe size
.TP
--stripe_cnt <count> 
A value of 0 for this means to stripe on all available OSTs. Default is 0.
.TP
--stripe_pattern <pattern> 
Only Pattern 0 (RAID 0) is supported currently.
.PP
.B --add ost 
Creates an OBD, OST, and OSC. The OST and OBD are created on the specified node.
.TP
--ost <name> 
Assign a name to the OST device.
.TP
--node <nodename> 
Node on which the OST service is run, can not be a profile node.
.TP
--dev <pathname> 
Path of device on local system. If this is a file, then a loop device is created and used as the block device.
.TP
--size [size] 
Optional argument indicating the size (in KB) of the device to be created (used typically for loop devices).
.TP
--obdtype 
obdfilter|obdecho 
.TP
--lov <name> 
Optional arguement. Name of LOV to which this OSC will be attached. 
.TP
--ostuuid UUID 
Specify the UUID of the OST device. 
.TP
--fstype 
extN|ext3 Optional arguement used to specify the file system type. Default is ext3.
.TP
--journal_size <size> 
Optional arguement to specify the journal size for the ext2/ext3 file system. The size should be in the units expected by mkfs, so for ext3 it should be in MB. If this is option is not used, the ext2/ext3 filesystem will be configured with the default journal size.
.PP
.B --add mtpt 
Creates a mount-point on the specified node. Either an LOV or OSC name can be used.
.TP
--node node 
Node that will use the mtpt.
.TP
--path /mnt/path 
The mount-point to use to mount Lustre filesystem
.TP
--mds mds_name 
MDS name
.TP
--ost ost_name | --lov lov_name
OST or LOV name as specified earlier in the configuration
.PP
.B --add route 
Creates a static route through a gateway to a specific nid or a range of nid's.
.TP
--node node 
Node to add the route to.
.TP
--gw nid 
The nid of the gateway (must be a local interface or a peer).
.TP
--tgt nid 
For a specific route, this is the target nid.
.TP
--lo nid 
For a range route, this is the lo value nid.
.TP
--hi nid 
For a range route, this is the hi value nid.
.PP
.B --add echo-client 
Used for testing purpose only. 
.TP
--node node 
Name of the node that echo client should run on,
.TP
--obd obd_name 
.SH OPTIONS
One of the following options should be specified.
.TP 12
--output filename 
Send output to the file. If the file exists, it will be overwritten.
.TP
--merge filename 
Add the new element to an existing file. 
.SH EXAMPLES
Real life examples are given in the Lustre-conf manual page.
.SH BUGS
None are known.
