.\" -*- nroff -*-
.\" Copyright (c) 2007, 2010, Oracle and/or its affiliates. All rights reserved.
.\" This file may be copied under the terms of the GNU Public License.
.\"
.\" Copyright (c) 2012, Intel Corporation.
.\"
.TH Lustre 7 "2006 Jun 15" Lustre "A high-performance cluster file system"
.SH NAME
Lustre
.SH SYNOPSIS
A high-performance file system designed for clusters.
.SH DESCRIPTION
.B Lustre®
is a high-performance, massively-scalable, POSIX-compliant network file system
designed for the world's largest high-performance compute clusters.

Lustre filesystems are made up of multiple services typically distributed
across multiple nodes.  Lustre clients can contact these server nodes over
multiple high-speed network fabrics via LNET, the Lustre NETworking
system.  Clients then present the filesystem at a mount point to userspace.

A filesystem is comprised of a 
.I MDT
, MetaData Target, which stores directory and file meta-information such as
file ownership, timestamps, access permissions, etc, and a
series of 
.I OSTs
, Object Storage Targets, which hold the file data in one or more objects.
There is typically not a 1:1 mapping of OST objects and what is presented
as a file on a Lustre client.

Lustre and LNET are implemented as a series of kernel modules, for both
servers and clients.  LNET networks are defined in the modprobe.conf file on
all nodes.  Lustre is started on the clients and servers using the
.BR mount (8)
command.

.SH COMMANDS
.TP
.BR mkfs.lustre (8)
Format a physical disk for use as a Lustre server's backend storage (aka
target).
.TP
.BR tunefs.lustre (8)
Modify configuration information on a Lustre target disk.
.TP
.BR mount.lustre (8)
A helper program for
.BR mount (8)
that starts Lustre servers and clients mounts the client filesystem.
.TP
.BR lctl (8)
A low-level interface to control various aspects of Lustre
.TP
.BR lfs (1)
A user-level interface to control Lustre-specific information for
individual files. 
.B lustre_config.sh
Format multiple Lustre targets simultaneously from definitions in a CSV
file.
.SH BUGS
Please report all bugs http://bugs.whamcloud.com/
.SH AVAILABILITY
.B The
.BR Lustre (7) 
filesystem package is available via
.br
http://downloads.whamcloud.com/
.SH SEE ALSO
.BR mkfs.lustre (8),
.BR tunefs.lustre (8),
.BR mount.lustre (8),
.BR lctl (8),
.BR lfs (1),
.BR lfs_migrate (1),
.BR liblustreapi (7),
.BR l_getgroups (8),
.BR llstat (8),
.BR ll_recover_lost_found_objs (8),
.BR llverdev (8),
.BR lst (8),
.BR llobdstat (8),
.BR ll_decode_filter_fid (8),
.BR llog_reader (8),
.BR lshowmount (8),
.BR lustre_rsync (8)
