.TH lustreapi 7 "2009 Aug 10" The Lustre user application interface library
.SH NAME
lustreapi \- The lustre API library
.SH DESCRIPTION
The lustreapi library provides functions to access and/or modify settings specific to the Lustre filesystem (allocation policies, quotas, etc).
.SH "SEE ALSO"
.BR lustre (7),
.BR llapi_file_create (3),
.BR llapi_file_open (3),
.BR llapi_file_get_stripe (3),
.BR llapi_layout (3),
.BR llapi_quotactl (3)
.BR llapi_hsm_state_get (3)
.BR llapi_hsm_state_set (3)
