.TH lwizard 1 "2003 Oct 29" Lustre "Configuration utilities"
.SH NAME
lwizard \- Lustre configuration wizard
.SH SYNOPSIS
.br
.B lwizard
.br
.B lwizard [--help]
.br
.BR lwizard  [-o|--file=CONFIG_FILE][--stripe_size=SIZE][--stripe_cnt=COUNT]
.SH DESCRIPTION
The configuration files for Lustre installation are generally created through a series of lmc commands, this generates an XML file which describes the complete cluster. The lwizard eliminates the need to learn lmc to generate configuration files, instead it achieves the same through asking some simple questions. The 
XML configuration file generated using lwizard will still have to be made accessible to all the cluster nodes either by storing it on an LDAP server, NFS or by copying it over to all the involved nodes and then running lconf on all nodes to start up the various Lustre services, device setups or mounting the filesystem. 
So, once invoked, lwizard asks a series of questions about the various pieces of the cluster : 
.TP
.B MDS hostname 
.TP
.B MDS device information 
.TP
.B OST hostname 
This will be asked for every new OST added 
.TP
.B OST device information 
This will be asked for every new OST added 
.TP
.B Lustre mount-point 
This is the Lustre mount-point on the client (default - /mnt/lustre) 

The wizard saves the XML file to the filename specified using the -o or --file option or the default file config.xml. It will also save the lmc commands used to create the XML file in a script config.sh or <specified-file-name>.sh. 

The lwizard tool currently assumes the following defaults: 

.TP
.B Network type
tcp 
.TP
.B Filesystem type
ext3 
.TP
.B LMC path
.I /usr/sbin/lmc 

.SH EXAMPLES
The example below shows a sample session using lwizard.
.PP
[username@meghna utils]$ ./lwizard --stripe_size=64 --stripe_cnt=2 
.br
This script will help you create a Lustre configuration file. 
.br
Creating mds "mds1"...
.br 
Please enter the hostname(s) for mds1: meghna 
.br
Please enter the device name or loop file name for meghna: /tmp/mds1 
.br
Please enter the device size or 0 to use entire device:5000 
.br
Creating ost "ost1"... 
.br
Please enter the hostname(s) for ost1: meghna 
.br
Please enter the device name or loop file name for meghna: /tmp/ost1 
.br
Please enter the device size or 0 to use entire device:10000 
.br
Creating ost "ost2"... 
.br
Please enter the hostname(s) for ost2: 
.br
Please enter the clients' mountpoint (/mnt/lustre): 
.br
Creating mds "mds2"... 
.br
Please enter the hostname(s) for mds2: 
.br
 mds1 lov1 ost1 client 
.br
Saving configuration to config.xml: 
.br
Your configuration has been saved to config.xml. 
.br
Your config command has been save to config.sh. 
.SH BUGS
None are known.
