.\" -*- nroff -*-
.\" Copyright 2006 by Cluster FileSystems.  All Rights Reserved.
.\" This file may be copied under the terms of the GNU Public License.
.\"
.TH mount.lustre 8 "2006 Jun 15" Lustre "configuration utilities"
.SH NAME
mount.lustre \- start a Lustre client or target service 
.SH SYNOPSIS
.br
.BI "mount \-t lustre [\-o " options "] " "device dir"
.SH DESCRIPTION
.B mount.lustre
is used to start a Lustre client or target service.  This program should not be
called directly; rather it is a helper program invoked through 
.BR mount (8)
as above.  Lustre clients and targets are stopped by using the 
.BR umount (8)
command.
.br

There are two forms for the 
.I device
option, depending on whether a client or a target service is started:
.TP
.BI <mgsspec>:/<fsname>
This is a client mount command to mount the Lustre filesystem named
<fsname> by contacting the Management Service at <mgsspec>.  The format for
<mgsspec> is defined below.
.TP
.BI <disk_device>
This starts the target service defined by the 
.I mkfs.lustre
command on the physical disk <disk_device>
.SH OPTIONS
.TP
.BI <mgsspec>:= <mgsnode>[:<mgsnode>]
The mgs specification may be a colon-separated list of nodes...
.TP
.BI <mgsnode>:= <mgsnid>[,<mgsnid>]
 ...and each node may be specified by a comma-separated list of NIDs.
.PP
In addition to the standard mount options, Lustre understands the following
additional options:
.TP
.BI flock
Enable flock support
.TP
.BI noflock
Disable flock support
.TP
.BI user_xattr
Enable get/set user xattr
.TP
.BI nouser_xattr
Disable user xattr
.TP
.BI acl
Enable ACL support
.TP
.BI noacl
Disable ACL support
.TP
.BI nosvc
Only start the MGC (and MGS, if co-located) for a target service, and not the actual service.
.TP
.BI exclude= ostlist
Start a client or MDT with a list of known inactive OSTs
.TP
.BI abort_recov
Abort recovery (targets only)
.SH EXAMPLES
.TP
.B mount -t lustre cfs21@tcp0:/testfs /mnt/myfilesystem
Start a client for the Lustre filesystem 'testfs' at the mount point
/mnt/myfilesystem. The Management Service is running on a node reachable
from this client via the nid cfs21@tcp0.
.TP
.B mount -t lustre /dev/sda1 /mnt/test/mdt
Start the Lustre target service on /dev/sda1.
.TP
.B mount -t lustre -L testfs-MDT0000 -o abort_recov /mnt/test/mdt
Start the testfs-MDT0000 service (by using the disk label), but abort the
recovery process.
.SH BUGS
Please report all bugs to Cluster FileSystems, support@clusterfs.com
.SH AVAILABILITY
.B mount.lustre
is part of the 
.BR Lustre (7) 
filesystem package and is available from CFS
.br
http://clusterfs.com
.SH SEE ALSO
.BR Lustre (7),
.BR mount (8),
.BR mkfs.lustre (8),
.BR tunefs.lustre (8),
.BR lctl (8),
.BR lfs (1)
