.TH PLOT-LLSTAT 8 2024-08-28 Lustre "Lustre Configuration Utilities"
.SH NAME
plot-llstat \- plot Lustre statistics
.SH SYNOPSIS
.SY plot-llstat
.I RESULTS_FILENAME
.RI [ PARAMETER_INDEX ]
.YS
.SH DESCRIPTION
The
.B plot-llstat
script is used to generate csv file and instructions files for gnuplot
from the output of
.BR llstat .
Since
.B llstat
is generic in nature,
.B plot-llstat
is also a generic script.
.PP
.I parameter_index
can be 1 for count per interval, 2 for count per second (default),
or 3 for total count.
.PP
plot-llstat script creates dat(csv) file using number of operations
specified by the user. Number of operations equals to number of columns in csv
file. And values in those columns are equals to the corresponding value of
the
.I PARAMETER_INDEX
parameter from the output file.
.PP
.B plot-llstat
also creates .scr file that contains instructions for gnuplot to plot
the graph. After generating .dat and .scr files
.B plot-llstat
invokes
.B gnuplot
to display graph.
.SH EXAMPLES
.EX
llstat -i2 -g -c lustre-OST0000 > log
plot-llstat log 3
.EE
.SH AVAILABILITY
.B plot-llstat
is part of the
.BR lustre (7)
filesystem package since release 1.4.0
.\" Added in commit 1.3.4-1213-g373ad7359d
.SH SEE ALSO
.BR llstat (8)
