.\" -*- nroff -*-
.\" Copyright 2008 by Sun Microsystems, Inc.  All Rights Reserved.
.\" This file may be copied under the terms of the GNU Public License, v2.
.\"
.TH tunefs.lustre 8 "2008 Mar 15" Lustre "configuration utilities"
.SH NAME
tunefs.lustre \- modify the Lustre configuration information on a disk
.SH SYNOPSIS
.br
.B tunefs.lustre
[options] 
.I device
.br
.SH DESCRIPTION
.B tunefs.lustre
is used to modify the configuration information on a Lustre target
disk. This includes upgrading old (pre-Lustre 1.6) disks.  This does not
reformat the disk or erase the target information, but modifying the
configuration information can result in an unusable filesystem.  You have
been warned.
.br
Changes made here will affect a filesystem only when the target is next
mounted.

.SH OPTIONS
.TP
.BI \--comment= comment
Set user comment about this disk, ignored by Lustre.
.TP
.BI \--dryrun
Only print what would be done; does not affect the disk
.TP
.BI \--erase-params
Remove all previous parameter info
.TP
.BI \--failnode= nid,...  
Set the NID(s) of a failover partner. This option can be repeated as desired.
.TP
.BI \--fsname= filesystem_name  
The Lustre filesystem this service will be part of.  Default is 'lustre'
.TP
.BI \--index= index
Force a particular OST or MDT index 
.TP
.BI \--mountfsoptions= opts
Set permanent mount options, equivalent to setting in /etc/fstab
.TP
.BI \--mgs
Add a configuration management service to this target
.TP
.BI \--mgsnode= nid,...  
Set the NID(s) of the MGS node, required for all targets other than the MGS.
.TP
.BI \--nomgs
Remove a configuration management service to this target
.TP
.BI \--quiet
Print less information.
.TP
.BI \--verbose
Print more information.
.TP
.BI \--writeconf
Erase all config logs for the filesystem that this MDT is part of, and
regenerate them.  This is very dangerous.  All clients and servers should
be stopped.
All targets must then be restarted to regenerate the logs.  
No clients should be started until all targets have restarted.
In general this should be executed on the MDT only, not the OSTs.

.SH EXAMPLES
.TP
.B tunefs.lustre --erase-param --mgsnode=<new_nid> --writeconf /dev/sda
Change the MGS NID address. (This should be done on every target disk,
since they should all be contacting the same MGS.)
.TP
.B tunefs.lustre --param="failover.node=192.168.0.13@tcp0" /dev/sda
Add a failover NID location for this target
.TP
.B tunefs.lustre --mgs --mdt --fsname=testfs /dev/sda
Upgrade an old 1.4.X Lustre MDT to 1.6. The new filesystem name is "testfs". 
.TP
.B tunefs.lustre --writeconf --mgs --mdt --fsname=testfs /dev/sda1
Upgrade an old 1.4.X Lustre MDT to 1.6, and start with brand-new 1.6
configuration logs. All old servers and clients must be stopped.

.SH BUGS
Please report all bugs to Sun Microsystems using http://bugzilla.lustre.org/
.SH AVAILABILITY
.B tunefs.lustre
is part of the 
.BR Lustre (7) 
filesystem package and is available from Sun Microsystems, Inc via
.br
http://downloads.lustre.org
.SH SEE ALSO
.BR lustre (7),
.BR mkfs.lustre (8),
.BR mount.lustre (8),
.BR lctl (8),
.BR lfs (1)
