# SPDX-License-Identifier: GPL-2.0

#
# This file is part of Lustre, http://www.lustre.org/
#

obj-m += osc.o
osc-objs := osc_request.o lproc_osc.o osc_dev.o osc_object.o osc_page.o \
	    osc_lock.o osc_io.o osc_quota.o osc_cache.o
