# SPDX-License-Identifier: GPL-2.0

#
# This file is part of Lustre, http://www.lustre.org/
#

#
# Copyright (c) 2025-2026, DDN/Whamcloud, Inc
#

obj-m += osd_wbcfs.o
osd_wbcfs-objs := osd_handler.o osd_object.o osd_hash.o osd_index_hash.o
osd_wbcfs-objs += osd_io.o osd_dirent.o osd_lproc.o wbcfs.o
